export type DialogueMap = {
    [langCode: string]: string[];
};

export const CHARACTER_DIALOGUES: DialogueMap = {
    'en': [
        "WAGMI! 🚀",
        "Feed me ~ I'm hungry for gains! 🍌",
        "Diamond Hands only! 💎",
        "Wen Lambo? Now! 🏎️",
        "Don't be a paper hand! 🧻",
        "Ape in strong! 🦍",
        "To the mooooon! 🌑",
        "Did someone say x100? 📈",
        "LFG!!! 🔥",
        "Top Chad energy! 💪",
        "Rent is due? Not anymore! 🏠",
        "Imagine selling now... 🤡",
        "Just one more feed... 🍬",
        "Cat needs new shoes (lambo)!",
        "FOMO is real! 👀",
        "Degen hours open! 🌙",
    ],
    'zh': [
        "梭哈是一种智慧! 🧠",
        "搏一搏，单车变摩托! 🏍️",
        "赢了会所嫩模，输了下地干活! 👷",
        "不要怂，就是干! 💪",
        "别墅靠大海! 🌊",
        "冲冲冲! 🚀",
        "我也要恰饭的嘛! 🍌",
        "此时不入更待何时?",
        "一币一别墅! 🏠",
        "做人要有梦想! ✨",
        "以前你对我爱搭不理，现在的我你高攀不起! 💅",
        "欧皇附体! 🍀",
        "这波稳了! 😎",
        "只有梭哈才能致富! 💰",
    ],
    'ko': [
        "가즈아아아! 🚀",
        "존버는 승리한다! 💎",
        "한강뷰 가자! 🏙️",
        "떡상 가즈아! 📈",
        "흑우 왔는가? (어서옵쇼) 🐮",
        "졸업하자! 🎓",
        "돔황차! (아니 들어와!) 🏃",
        "풀매수 때려! 🍌",
        "야수의 심장으로! ❤️",
        "오늘 저녁은 치킨이다! 🍗",
        "구조대? 내가 구조대다! 🚑",
        "뇌동매매 멈춰! (농담, 더 해!) 🛑",
    ],
    'ru': [
        "Туземун! 🚀",
        "Где моя Ламба? 🏎️",
        "На завод не пойду! 🏭",
        "Ходл до талого! 💎",
        "Залетай на всю котлету! 🥩",
        "Это ГЕМ, братан! 💎",
        "Не будь хомяком! 🐹",
        "ФОМО не дремлет! 👀",
        "Крипто-зима отменяется! ☀️",
        "Заноси бабки! 💰",
        "Кто не рискует, тот не пьет шампанское! 🍾",
        "Иксы неизбежны! ✖️",
    ],
    'id': [
        "Gas terus bosku! 🔥",
        "Otw Sultan! 👑",
        "Jangan kasih kendor! 💪",
        "Cuan luber bos! 💰",
        "Kaum rebahan rise up! 🛌",
        "To the moon! 🚀",
        "Serok bawah bos! 📉",
        "Anti rungkad club! 🛡️",
        "Gajian tiap hari! 📅",
        "Makan pisang dulu biar kuat! 🍌",
        "Rezeki anak soleh! 🙏",
        "Jangan lupa sedekah (ke kucing)! 😻",
    ],
    'ms': [
        "Padu bossku! 🔥",
        "Masyukkk! 💰",
        "Jangan koyak! 💪",
        "Kasi licin! 🧹",
        "Kita ke bulan! 🚀",
        "Rezeki jangan ditolak! 🙌",
        "Belanja sikit boss! 🍌",
        "Hinggap bulan terus! 🌑",
        "Auto kaya! 🤑",
        "Sampai jadi! 💎",
        "Durian runtuh ni! 🍈",
        "On x On? ON!",
    ],
    'vi': [
        "Đói quá, donate chuối đi người anh em! 🍌",
        "Thử nhân phẩm cái nào!",
        "Cơ hội đổi đời tới rồi!",
        "BanMao là nhất, nhất là BẠN!",
        "Hũ to vầy không húp phí lắm! 💰",
        "Đại gia ơi, bao nuôi em đi!",
        "Cùng nhau lên cung trăng nào!",
        "Meo meo... à nhầm, Gâu gâu?",
        "Nhìn chát (chart) nến xanh mà phê 📈",
        "Hold chặt chuối (và ví) nha!",
        "Vía may mắn nè, nhận lấy! ✨",
        "Lên thuyền chưa hay còn ở đảo?",
        "Sắm phi thuyền đi là vừa!",
        "Cho xin miếng bánh nào sen ơi?",
        "Nhìn tướng là biết sắp giàu rồi!",
        "Đại gia ơi, nổ hũ đi nào!",
        "Chơi là trúng, không trúng thì trượt!",
    ],
    'ja': [
        "頑張って! (Ganbatte!)",
        "バナナ大好き! (Banana daisuki!)",
        "月に行きましょう! (Tsuki ni ikimashou!)",
        "幸運を祈ります!",
        "すごいですね!",
        "一緒に勝ちましょう!",
        "にゃー... おっと!",
        "大当たり!",
    ],
    'es': [
        "¡Buena suerte!",
        "¡Vamos a la luna!",
        "¡Dame plátanos! 🍌",
        "¡No te lo pierdas!",
        "¡El premio es enorme!",
        "¡Eres el mejor!",
        "¡Ganemos juntos!",
    ],
    'fr': [
        "Bonne chance!",
        "Allons sur la lune!",
        "J'aime les bananes! 🍌",
        "Ne manquez pas ça!",
        "Le jackpot est énorme!",
        "Tu es le meilleur!",
    ],
    'th': [
        "ขอให้โชคดี (Khor hai chok dee)",
        "ไปดวงจันทร์กันเถอะ! 🚀",
        "ขอกล้วยหน่อย! 🍌",
        "รวยๆ เฮงๆ!",
        "สู้ๆ นะ!",
    ]
};
