// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;
// Generated by tools/sync-king-direction.cjs
library BanmaoKingDirection {
function leftTime(uint8 id) internal pure returns(string memory){
if(id==0)return "0;.1;.24;.36;.5;.76;1";
if(id==1)return "0;.12;.25;.38;.52;.7;1";
if(id==2)return "0;.12;.28;.4;.56;.8;1";
if(id==3)return "0;.16;.32;.48;.64;.84;1";
if(id==4)return "0;.12;.3;.43;.65;.84;1";
if(id==5)return "0;.26;.3;.43;.58;.82;1";
if(id==6)return "0;.12;.3;.43;.58;.82;1";
if(id==7)return "0;.12;.3;.43;.58;.82;1";
if(id==8)return "0;.16;.3;.46;.62;.82;1";
if(id==9)return "0;.12;.3;.43;.58;.82;1";
if(id==10)return "0;.12;.3;.43;.58;.82;1";
if(id==11)return "0;.12;.3;.43;.58;.82;1";
if(id==12)return "0;.18;.36;.52;.68;.87;1";
if(id==13)return "0;.17;.35;.48;.65;.88;1";
if(id==14)return "0;.1;.25;.4;.55;.78;1";
if(id==15)return "0;.12;.3;.43;.58;.82;1";
if(id==16)return "0;.12;.25;.5;.75;.88;1";
if(id==17)return "0;.16;.32;.46;.64;.85;1";
if(id==18)return "0;.16;.28;.42;.56;.84;1";
if(id==19)return "0;.17;.34;.51;.68;.85;1";
if(id==20)return "0;.12;.3;.43;.58;.82;1";
revert("Invalid expression");}
function rightTime(uint8 id) internal pure returns(string memory){
if(id==0)return "0;.14;.29;.42;.57;.81;1";
if(id==1)return "0;.14;.27;.4;.54;.72;1";
if(id==2)return "0;.09;.24;.38;.54;.78;1";
if(id==3)return "0;.18;.34;.5;.66;.86;1";
if(id==4)return "0;.12;.3;.43;.65;.84;1";
if(id==5)return "0;.28;.325;.455;.605;.84;1";
if(id==6)return "0;.12;.3;.43;.58;.82;1";
if(id==7)return "0;.12;.3;.43;.58;.82;1";
if(id==8)return "0;.08;.22;.38;.54;.74;1";
if(id==9)return "0;.12;.3;.43;.58;.82;1";
if(id==10)return "0;.12;.3;.43;.58;.82;1";
if(id==11)return "0;.12;.3;.43;.58;.82;1";
if(id==12)return "0;.12;.3;.46;.65;.85;1";
if(id==13)return "0;.12;.3;.43;.6;.83;1";
if(id==14)return "0;.17;.32;.47;.62;.85;1";
if(id==15)return "0;.12;.3;.43;.58;.82;1";
if(id==16)return "0;.12;.25;.5;.75;.88;1";
if(id==17)return "0;.2;.36;.5;.68;.89;1";
if(id==18)return "0;.1;.22;.36;.5;.78;1";
if(id==19)return "0;.21;.38;.55;.72;.89;1";
if(id==20)return "0;.12;.3;.43;.58;.82;1";
revert("Invalid expression");}
function ease(uint8 id) internal pure returns(string memory){
if(id==0)return ".25 0 .45 1";
if(id==1)return ".2 0 .35 1";
if(id==2)return ".3 0 .5 1";
if(id==3)return ".4 0 .6 1";
if(id==4)return ".4 0 .6 1";
if(id==5)return ".1 0 .25 1";
if(id==6)return ".4 0 .6 1";
if(id==7)return ".4 0 .6 1";
if(id==8)return ".2 0 .4 1";
if(id==9)return ".3 0 .6 1";
if(id==10)return ".25 0 .5 1";
if(id==11)return ".4 0 .6 1";
if(id==12)return ".4 0 .6 1";
if(id==13)return ".3 0 .55 1";
if(id==14)return ".25 0 .5 1";
if(id==15)return ".4 0 .6 1";
if(id==16)return ".3 0 .6 1";
if(id==17)return ".45 0 .65 1";
if(id==18)return ".18 0 .35 1";
if(id==19)return ".42 0 .58 1";
if(id==20)return ".3 0 .6 1";
revert("Invalid expression");}
function wrist(uint8 id) internal pure returns(string memory){
if(id==0)return "0;0;-10;12;-10;2;0";
if(id==1)return "0;3;-12;7;-4;0;0";
if(id==2)return "0;0;-6;12;-3;1;0";
if(id==3)return "0;10;14;-7;-10;2;0";
if(id==4)return "0;0;-2;-2;-1;3;0";
if(id==5)return "0;0;-4;-4;-2;0;0";
if(id==6)return "0;-2;-8;-6;-6;-1;0";
if(id==7)return "0;0;-1;-2;-2;0;0";
if(id==8)return "0;-4;12;-12;10;-2;0";
if(id==9)return "0;-1;-6;-3;-3;-3;0";
if(id==10)return "0;-2;-8;-6;-8;-2;0";
if(id==11)return "0;0;-2;-2;-1;0;0";
if(id==12)return "0;-3;-16;-20;-16;-4;0";
if(id==13)return "0;3;12;-8;-4;1;0";
if(id==14)return "0;-2;-10;8;-10;-2;0";
if(id==15)return "0;0;2;-2;2;0;0";
if(id==16)return "0;0;-2;-2;-1;-1;0";
if(id==17)return "0;2;9;12;9;2;0";
if(id==18)return "0;-2;-8;-5;-8;-2;0";
if(id==19)return "0;-1;-4;3;5;1;0";
if(id==20)return "0;-1;-6;4;4;4;0";
revert("Invalid expression");}
function tail(uint8 id) internal pure returns(string memory){
if(id==0)return "0;2;16;-12;10;3;0";
if(id==1)return "0;4;-18;15;-8;2;0";
if(id==2)return "0;-3;12;18;5;-2;0";
if(id==3)return "0;-2;-7;3;10;4;0";
if(id==4)return "0;0;0;1;5;3;0";
if(id==5)return "0;0;-8;-8;-3;0;0";
if(id==6)return "0;-1;-3;-3;-3;-1;0";
if(id==7)return "0;0;1;2;2;1;0";
if(id==8)return "0;4;-17;18;-16;5;0";
if(id==9)return "0;0;-1;-2;-2;-2;0";
if(id==10)return "0;0;6;-5;6;1;0";
if(id==11)return "0;0;1;2;1;0;0";
if(id==12)return "0;0;-2;-1;2;1;0";
if(id==13)return "0;-2;-8;7;11;3;0";
if(id==14)return "0;0;1;-2;1;0;0";
if(id==15)return "0;0;1;-1;1;0;0";
if(id==16)return "0;0;-3;-3;3;3;0";
if(id==17)return "0;2;8;12;7;3;0";
if(id==18)return "0;2;-14;16;-10;2;0";
if(id==19)return "0;-3;-8;0;9;4;0";
if(id==20)return "0;0;-2;-3;-3;-3;0";
revert("Invalid expression");}
function wristLeft(uint8 id) internal pure returns(string memory){
if(id==0)return "0;1;5;-3;5;1;0";
if(id==1)return "0;-2;10;-5;3;0;0";
if(id==2)return "0;0;2;1;2;0;0";
if(id==3)return "0;-6;-12;5;9;-1;0";
if(id==4)return "0;2;16;16;3;-3;0";
if(id==5)return "0;-1;8;5;2;0;0";
if(id==6)return "0;1;3;2;2;1;0";
if(id==7)return "0;3;15;-7;13;2;0";
if(id==8)return "0;1;-3;4;-2;0;0";
if(id==9)return "0;1;3;2;2;2;0";
if(id==10)return "0;1;3;2;3;1;0";
if(id==11)return "0;2;5;7;5;2;0";
if(id==12)return "0;0;3;4;3;1;0";
if(id==13)return "0;-1;-4;3;2;0;0";
if(id==14)return "0;1;8;-6;10;1;0";
if(id==15)return "0;-1;-2;2;-2;-1;0";
if(id==16)return "0;1;3;3;1;1;0";
if(id==17)return "0;-1;-7;-10;-8;-1;0";
if(id==18)return "0;1;3;1;3;0;0";
if(id==19)return "0;0;1;-1;-1;0;0";
if(id==20)return "0;0;2;-1;-1;-1;0";
revert("Invalid expression");}
}
