import { BANMAO_KING_DEPLOYMENT as deployment } from "./deployment";

// Public addresses only. Do not import local deployment tooling or secrets here.
export const KING_CONTRACTS = [
  { name: "BanmaoKingNFT", address: deployment.contractAddress, reused: false, vi: "Hợp đồng NFT ERC-721: mint bằng BANMAO, quản lý quyền sở hữu, cấp tổ hợp trait không trùng, gọi renderer để lấy metadata và công bố royalty 2%.", en: "ERC-721 collection: BANMAO minting, ownership, unique trait allocation, renderer-backed metadata and 2% royalty information." },
  { name: "BanmaoKingRenderer", address: deployment.rendererAddress, reused: false, vi: "Ghép thân, biểu cảm, phụ kiện, nền, huy hiệu và chuyển động thành SVG; tạo metadata JSON hoàn toàn on-chain. Các địa chỉ artwork và motion là bất biến.", en: "Composes body, expression, accessories, background, badge and motion into SVG and on-chain JSON metadata. Artwork and motion addresses are immutable." },
  { name: "BanmaoKingMotionPart0", address: "0x3685dB8Bf428Da0931ce838cC65F2717568b43cE", reused: false, vi: "Cung cấp phần chuyển động biểu cảm, phụ kiện và nền cho renderer mới; không chứa CSS reduced-motion đóng băng ảnh.", en: "Supplies expression, accessory and background motion for the new renderer, without reduced-motion freezing CSS." },
  { name: "BanmaoKingMotionPart1", address: "0x1f7BdAe52267da4D78f438e219dB06abE0fF0751", reused: false, vi: "Cung cấp phần chuyển động bổ sung, tư thế và đuôi; được renderer tạo một lần khi triển khai.", en: "Supplies additional motion, poses and tail animation; created once by the renderer at deployment." },
  { name: "BanmaoKingBodyLib", address: "0x0bD84D6190AD71B3dF501324D8b13b2c13F29f8E", reused: true, vi: "Danh mục thân và màu sắc; kết hợp dữ liệu hình thể từ AnatomyPart để tạo lớp SVG thân.", en: "Body and color catalogue; combines AnatomyPart geometry into the body SVG layer." },
  { name: "BanmaoKingAnatomyPart", address: "0x89367489ECcA9A62c435EaDC1ef85Eee2de91B96", reused: true, vi: "Lưu các mảnh SVG hình thể dùng chung cho BodyLib, tách nhỏ dữ liệu artwork.", en: "Stores shared anatomy SVG fragments used by BodyLib, splitting artwork data into a separate contract." },
  { name: "BanmaoKingExpressionLib", address: "0x7134367C9ef3EEEB25feDDe26F9c827F327Fd863", reused: true, vi: "Danh mục 12 biểu cảm; chuyển yêu cầu render đến một trong ba ExpressionPart theo trait ID.", en: "Catalogue of 12 expressions; routes rendering to one of three ExpressionPart contracts by trait ID." },
  { name: "BanmaoKingExpressionPart0", address: "0x9017020aC50DEF0e9925BF1e61031A7043ced345", reused: true, vi: "SVG biểu cảm 0–3: Happy Smile, Joy, Wink, Love Eyes.", en: "Expression SVGs 0–3: Happy Smile, Joy, Wink, Love Eyes." },
  { name: "BanmaoKingExpressionPart1", address: "0x3bC130aB69367902E425E0981FBd7bF128E0B67c", reused: true, vi: "SVG biểu cảm 4–7: Sleepy, Surprised, Determined, Teary.", en: "Expression SVGs 4–7: Sleepy, Surprised, Determined, Teary." },
  { name: "BanmaoKingExpressionPart2", address: "0xC6cb00768Fe934D8DDb1C0D13218579393532Ce0", reused: true, vi: "SVG biểu cảm 8–11: Silly, Cool Gaze, Starstruck, Zen.", en: "Expression SVGs 8–11: Silly, Cool Gaze, Starstruck, Zen." },
  { name: "BanmaoKingAccessoryLib", address: "0x87062C5E4fE19826bbc3FeCc961F77c300b87C28", reused: true, vi: "Danh mục phụ kiện và các lớp SVG phụ kiện để renderer ghép vào nhân vật.", en: "Accessory catalogue and SVG layers composed into the character by the renderer." },
] as const;
