import type { KingCopy } from "./en";
export const vi: KingCopy = {
collection: "Bộ sưu tập", explore: "Khám phá", mint: "Mint NFT", guide: "Cách mint", contracts: "Hợp đồng", language: "Ngôn ngữ", connect: "Kết nối ví",
kicker: "X LAYER · BỘ SƯU TẬP HOÀN TOÀN ON-CHAIN", title: "Chuối nhỏ bé.", titleAccent: "Khí chất nhà vua.", description: "Khám phá 9.216 tổ hợp nghệ thuật chuyển động độc đáo. Banmao King của bạn được lưu trữ hoàn toàn trên X Layer.",
combinations: "Tổ hợp độc đáo", layers: "Lớp nghệ thuật", onchain: "Nghệ thuật on-chain", price: "Giá mint", supply: "Đã mint", balance: "Số dư của bạn", gas: "Phí mạng thanh toán bằng OKB",
studio: "Khám phá bộ sưu tập", studioDesc: "Phối màu sắc, biểu cảm và phụ kiện. Tìm diện mạo bạn yêu thích.", preview: "Bản phối thử", randomize: "Ngẫu nhiên", reset: "Đặt lại đặc điểm", body: "Thân", expression: "Biểu cảm", accessory: "Phụ kiện", background: "Phông nền", animated: "SVG động · Luôn bật",
previewTitle: "CHỈ XEM TRƯỚC — KHÔNG CHỌN ĐỂ MINT", previewNote: "Các nút này không đặt giữ hay quyết định NFT nhận được. Hợp đồng cấp tổ hợp chưa từng mint. Seed công khai nên kết quả có thể tính trước, không phải ngẫu nhiên chống thao túng.",
featuresTitle: "Nhân vật nhỏ. Nghệ thuật bền lâu.", feature1: "Lưu trữ on-chain", feature1Desc: "Hình SVG và metadata JSON được tạo bởi hợp đồng, không phụ thuộc máy chủ lưu ảnh bên ngoài.", feature2: "Sống động từng nét", feature2Desc: "Biểu cảm, phụ kiện và tư thế chuyển động nhờ SVG động.", feature3: "Mỗi tổ hợp, một nhà vua", feature3Desc: "8 thân × 12 biểu cảm × 12 phụ kiện × 8 nền. Không trùng tổ hợp đặc điểm.",
guideDesc: "Ba bước từ kết nối ví đến nhận NFT.", step1: "Chuẩn bị ví", step1Desc: "Kết nối ví X Layer. Chuẩn bị BANMAO để mint và OKB để thanh toán phí mạng.", step2: "Chọn người nhận", step2Desc: "Chọn ví nhận và số lượng NFT. Kiểm tra địa chỉ người nhận cùng tổng thanh toán trước khi tiếp tục.", step3: "Xác nhận & nhận NFT", step3Desc: "Cấp quyền BANMAO nếu cần, rồi xác nhận mint riêng trong ví. Xem NFT và tải ảnh sau khi giao dịch hoàn tất.", faqTitle: "Thông tin cần biết", faq1: "Có thể mint hình đang xem trước không?", faq1Answer: "Không. Công cụ chỉ hiển thị các tổ hợp có thể có. Hợp đồng cấp đặc điểm từ seed công khai; kết quả có thể tính trước, không phải ngẫu nhiên bảo mật.", faq2: "Vì sao cần cả BANMAO và OKB?", faq2Answer: "BANMAO trả giá NFT. OKB trả phí mạng X Layer cho giao dịch cấp quyền và mint. Không gửi token trực tiếp đến hợp đồng artwork.", faq3: "Có cần refresh metadata sau mint không?", faq3Answer: "Không yêu cầu giao dịch bổ sung. Hợp đồng phát event khi mint. Marketplace có thể cần thời gian cập nhật và một số nơi chỉ hiển thị ảnh tĩnh.", contractDesc: "NFT → Renderer → Artwork & Motion. Bốn hợp đồng mới dùng lại bảy hợp đồng artwork. NFT cũ không tự chuyển sang bộ sưu tập này.", safety: "Chỉ cấp quyền BANMAO cho hợp đồng NFT. Không gửi token trực tiếp đến hợp đồng dựng hình. Xác minh mã nguồn không đồng nghĩa đã audit độc lập.", newContract: "Triển khai mới", reused: "Artwork tái sử dụng", payment: "Token thanh toán BANMAO · ERC-20", explorer: "Xem trên Explorer (tab mới)", copy: "Sao chép địa chỉ", copied: "Đã sao chép địa chỉ", copyFailed: "Không thể sao chép. Hãy chọn địa chỉ và sao chép thủ công.", technical: "Các hợp đồng artwork & chuyển động", royalty: "Royalty 2% · tùy marketplace", footer: "Nghệ thuật chuyển động. Hoàn toàn on-chain.",
loading: "Đang tải dữ liệu on-chain…", waiting: "Chờ dữ liệu", processing: "Đang xử lý…", soldOut: "Đã mint hết", insufficient: "Không đủ BANMAO", approve: "1/2 · Cấp quyền 6.666 BANMAO", mintAction: "2/2 · Mint NFT", resetAllowance: "Đặt lại quyền cũ", switchNetwork: "Chuyển sang X Layer", switchHelp: "Vui lòng chuyển mạng trong ví.", readError: "Chưa kết nối được X Layer. Không thể mint khi chưa xác thực dữ liệu.", retry: "Thử tải lại dữ liệu", mintNote: "NFT về ví đang kết nối. Đặc điểm xem trước không quyết định NFT mint.", transaction: "Xem giao dịch", success: "Mint thành công!", reloadImage: "Tải lại ảnh NFT", imageError: "NFT đã mint; chưa tải được ảnh. Hãy thử tải lại.", download: "Tải SVG động gốc", confirmed: "Đã xác nhận. Dữ liệu cập nhật tự động.", reverted: "Giao dịch bị revert; chưa mint NFT.", submitted: "Đã gửi. Đang chờ xác nhận…", pendingWarning: "Đã gửi; kiểm tra Explorer trước khi thử lại. Không gửi trùng.", allowanceUpdated: "Quyền đã thay đổi. Chờ dữ liệu mới trước khi xác nhận bước tiếp theo.", walletChanged: "Ví đã thay đổi. Hãy kết nối lại.", needGas: "Bạn cần OKB để trả phí mạng.", configError: "Cấu hình hợp đồng không khớp. Đã chặn mint.", transactionError: "Chưa thể giao dịch. Kiểm tra ví và thử lại.", rejected: "Bạn đã từ chối trong ví. Chưa gửi giao dịch mới.", details: "Chi tiết kỹ thuật", postMint: "Hợp đồng phát event khi mint. Không cần ký refresh bổ sung. Marketplace có thể cần thời gian cập nhật.", verified: "Mã nguồn đã xác minh · X Layer",
};
