import { clientMessagesForRequestContext, createClientRequestId, deriveSurface, initialClientState, migratePersistedModel, reduceClientState, SUGGESTED_PROMPTS } from "../../lib/ai/client/state";
import { parseAIStreamBlock } from "../../lib/ai/contracts";

test("creates a valid UUID request id without crypto.randomUUID on insecure LAN origins",()=>{const values=new Uint8Array(16);for(let index=0;index<values.length;index++)values[index]=index;const id=createClientRequestId({getRandomValues:<T extends ArrayBufferView>(array:T)=>{new Uint8Array(array.buffer,array.byteOffset,array.byteLength).set(values);return array;}});expect(id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);});
test("derives context only from pathname",()=>{expect(deriveSurface("/defi/stake")).toBe("defi");expect(deriveSurface("/gamefi/x")).toBe("gamefi");expect(deriveSurface("/collection/1")).toBe("collection");expect(deriveSurface("/unknown")).toBe("landing");});
test("authoritative metadata accepts only the singleton model",()=>{let state=initialClientState();expect(state.model).toBeNull();state=reduceClientState(state,{type:"models",models:["banmao.fun"],defaultModel:"banmao.fun"});expect(state).toMatchObject({model:"banmao.fun",models:["banmao.fun"]});expect(()=>reduceClientState(state,{type:"models",models:["banmao.fun","other" as never],defaultModel:"banmao.fun"})).toThrow("Invalid model metadata");});
test.each(["open9","xenon1"])("persisted removed model %s migrates explicitly to banmao.fun",(model)=>{expect(migratePersistedModel(model)).toEqual({model:"banmao.fun",migrated:true});const state=reduceClientState(initialClientState(),{type:"restore",state:{messages:[],tools:[],citations:[]},model,migrated:true});expect(state).toMatchObject({model:"banmao.fun",notice:"MODEL_MIGRATED"});});
test("other invalid persisted models fail closed without fallback",()=>{expect(()=>migratePersistedModel("other")).toThrow("Invalid persisted model");});
test("stream lifecycle supports timestamps, stop and clear without durable memory",()=>{let state=reduceClientState(initialClientState("banmao.fun"),{type:"start",message:"hello",createdAt:123});state=reduceClientState(state,{type:"delta",text:"hi"});expect(state.messages.at(-1)).toMatchObject({content:"hi",createdAt:123});expect(reduceClientState(state,{type:"stop"}).status).toBe("idle");expect(reduceClientState(state,{type:"clear"}).messages).toEqual([]);});
test("keeps completed tab-local turns as request context without persistence",()=>{const messages=[{role:"user" as const,content:"kiểm tra nft banmaobox 1",createdAt:1},{role:"assistant" as const,content:"RPC hiện không phản hồi",createdAt:2}];expect(clientMessagesForRequestContext(messages,"idle")).toEqual(messages);});
test("excludes interrupted and retried trailing turns from request context",()=>{const messages=[{role:"user" as const,content:"old",createdAt:1},{role:"assistant" as const,content:"done",createdAt:2},{role:"user" as const,content:"current",createdAt:3},{role:"assistant" as const,content:"partial",createdAt:4}];expect(clientMessagesForRequestContext(messages,"interrupted").at(-1)).toMatchObject({content:"partial",status:"interrupted"});expect(clientMessagesForRequestContext(messages,"interrupted",true).map((item)=>item.content)).toEqual(["old","done"]);});
test("tracks tool activity, citations and the retry prompt",()=>{let state=reduceClientState(initialClientState("banmao.fun"),{type:"start",message:"show staking"});state=reduceClientState(state,{type:"tool",tool:{callId:"1",name:"defi.staking",status:"available",source:"xlayer",summary:"read"}});state=reduceClientState(state,{type:"citation",citation:{sourcePath:"docs/ai/README.md",version:"1"}});expect(state).toMatchObject({lastPrompt:"show staking",tools:[{name:"defi.staking"}],citations:[{sourcePath:"docs/ai/README.md"}]});expect(SUGGESTED_PROMPTS.defi).toContain("Show the live staking protocol status");});
test("coalesces running and terminal activity for the same tool call",()=>{let state=initialClientState("banmao.fun");state=reduceClientState(state,{type:"tool",tool:{callId:"price-1",name:"onchainos.priceInfo",status:"running",source:"banmao-ai:tool-registry",summary:"Reading approved source"}});state=reduceClientState(state,{type:"tool",tool:{callId:"price-1",name:"onchainos.priceInfo",status:"unavailable",source:"okx:onchainos:price-info",summary:"Source unavailable"}});expect(state.tools).toEqual([{callId:"price-1",name:"onchainos.priceInfo",status:"unavailable",source:"okx:onchainos:price-info",summary:"Source unavailable"}]);});
test("stores bounded structured Collection media and resets it per request",()=>{let state=reduceClientState(initialClientState("banmao.fun"),{type:"start",message:"find happy"});state=reduceClientState(state,{type:"collection_results",payload:{callId:"1",observedAt:"2026-08-10T00:00:00.000Z",searchMode:"metadata",results:[{publicId:"banmao/Happy_Smile",secureUrl:"https://example.com/a.png",thumbnailUrl:"https://example.com/t.png",name:"Happy Smile",folder:"banmao",width:100,height:50,format:"png",score:48,matchedTerms:["happy"],matchReason:"public_id",searchMode:"metadata",observedAt:"2026-08-10T00:00:00.000Z"}]}});expect(state.collectionResults?.results).toHaveLength(1);state=reduceClientState(state,{type:"start",message:"next"});expect(state.collectionResults).toBeUndefined();});
test("AI media results remain in an independent state domain",()=>{const state=reduceClientState(initialClientState("banmao.fun"),{type:"start",message:"cyberpunk"});expect(Object.keys(state)).not.toEqual(expect.arrayContaining(["allImages","nextCursor","currentPage","searchQuery","sortBy","pageCache"]));expect(reduceClientState({...state,collectionResults:{callId:"1",observedAt:"now",searchMode:"metadata",results:[]}}, {type:"start",message:"happy"}).collectionResults).toBeUndefined();});
test("shared SSE parser fails closed and bounds incomplete events",()=>{expect(parseAIStreamBlock('event: done\ndata: {"requestId":"r","finishReason":"stop"}\n\n').event?.event).toBe("done");expect(()=>parseAIStreamBlock("event: unknown\ndata: {}\n\n")).toThrow("MALFORMED_SSE_EVENT");expect(()=>parseAIStreamBlock('event: delta\ndata: {"text":4}\n\n')).toThrow("MALFORMED_SSE_EVENT");expect(()=>parseAIStreamBlock("x".repeat(65537))).toThrow("SSE_EVENT_TOO_LARGE");});
test("accepts bounded status and heartbeat lifecycle events",()=>{expect(parseAIStreamBlock('event: status\ndata: {"requestId":"r","phase":"connecting","attempt":1,"elapsedMs":2}\n\n').event?.event).toBe("status");expect(parseAIStreamBlock('event: heartbeat\ndata: {"requestId":"r","phase":"streaming","elapsedMs":10000}\n\n').event?.event).toBe("heartbeat");});
test("partial output remains explicitly interrupted until a valid done event",()=>{let state=reduceClientState(initialClientState("banmao.fun"),{type:"start",message:"hello"});state=reduceClientState(state,{type:"delta",text:"partial"});state=reduceClientState(state,{type:"interrupted",message:"STREAM_INTERRUPTED"});expect(state).toMatchObject({status:"interrupted",error:"STREAM_INTERRUPTED"});expect(state.messages.at(-1)?.content).toBe("partial");});
