import { createTabMemory } from "../../lib/ai/client/memory";
test("tab memory is opt-in bounded and isolated",()=>{const a=createTabMemory({maxTurns:2,ttlMs:1000}),b=createTabMemory({maxTurns:2,ttlMs:1000});expect(a.export()).toEqual([]);a.setOptIn(true);a.append({role:"user",content:"one"},0);a.append({role:"assistant",content:"two"},1);a.append({role:"user",content:"three"},2);expect(a.export(2)).toHaveLength(2);expect(b.export()).toEqual([]);a.clear();expect(a.export()).toEqual([]);});

test("tab memory derives bounded episodic cues without durable storage",()=>{const memory=createTabMemory({maxTurns:20,ttlMs:1000});memory.setOptIn(true);memory.append({role:"user",content:"Please verify staking risks and lock mechanics"},0);expect(memory.snapshot(1)).toMatchObject({history:[{role:"user"}]});expect(memory.snapshot(1).episodic.recentMotifs).toEqual(expect.arrayContaining(["risk and verification","staking and lock mechanics"]));expect(memory.snapshot(1001).history).toEqual([]);});


function storage() { const data = new Map<string,string>(); return { getItem:(key:string)=>data.get(key)??null, setItem:(key:string,value:string)=>{data.set(key,value)}, removeItem:(key:string)=>{data.delete(key)} }; }
test("opt-in memory persists versioned bounded data and disable removes it",()=>{const store=storage();const a=createTabMemory({maxTurns:2,ttlMs:1000,storage:store,storageKey:"m"});a.setOptIn(true);a.append({role:"user",content:"one"},10);const b=createTabMemory({maxTurns:2,ttlMs:1000,storage:store,storageKey:"m"});b.setOptIn(true,11);expect(b.export(11)).toEqual([{role:"user",content:"one"}]);b.setOptIn(false);expect(store.getItem("m")).toBeNull();});
test("persistent memory rejects unknown versions",()=>{const store=storage();store.setItem("m",JSON.stringify({version:999,turns:[{turn:{role:"user",content:"secret"},at:1,topics:[],motifs:[]}]}));const m=createTabMemory({maxTurns:2,ttlMs:10,storage:store,storageKey:"m"});m.setOptIn(true,20);expect(m.export(20)).toEqual([]);expect(store.getItem("m") || "").not.toContain("secret");});
