// English translations
import type { LandingTranslations } from './index';

export const en: LandingTranslations = {
    logoTitle: "BANMAO NEBULA",
    tokenStats: "TOKEN STATS",
    totalSupply: "TOTAL SUPPLY:",
    circulating: "Circulating",
    burned: "Burned",
    tokenDistribution: "Token Distribution",
    holders: "HOLDERS",
    globalHolders: "GLOBAL HOLDERS",
    marketCap: "Market Cap",
    liquidity: "Liquidity",
    token: "Token",
    time: "Time",
    priceFeed: "PRICE FEED",
    network: "NETWORK:",
    price: "PRICE:",
    change24h: "24H CHANGE",
    mcap: "MCAP:",
    buyToken: "BUY $banmao",
    joinMission: "JOIN MISSION",
    gamefi: "GameFi",
    collection: "Collection",
    installApp: "INSTALL APP",
    installDesc: "Add to home screen for faster access!",
    installNow: "Install Now",
    howToInstall: "How to Install",
    language: "LANGUAGE",
    selectLang: "Select Language",
    settings: "SETTINGS",
    theme: "THEME",
    sound: "SOUND",
    minimizedApps: "MINIMIZED APPS",
    clickToRestore: "Click to restore",
    appsMinimized: "apps minimized",
    volume24h: "24H Volume",
    transactions24h: "24H Trades",
    totalTradeVolume: "$banmao Traded",
    community: "COMMUNITY",
    joinUs: "Join Us",
    dataVoid: "DATA VOID",
    dataVoidWarning: "⚠️ Delete ALL data?",
    dataVoidConfirm: "YES, RESET",
    dataVoidCancel: "CANCEL",
    dataVoidCleared: "✓ All data cleared!",
    tokenInfoTitle: "ABOUT BANMAO",
    tokenInfoDesc: "Banmao is born from the playful fusion of a cat 🐱 and banana 🍌. The name blends English and Chinese — \"Banana\" and \"Māo (猫, cat in Chinese)\" — creating Banmao, a symbol of humor, unity, and creativity. It's not just a name, but a spirit of combining East and West, fun and meaning, to build a living meme.",
    totalBurned: "TOTAL BURNED 🔥",
    burnHistory: "View History & Donations",
    burnDescription: "Burn history & community wallet donations. All $BANMAO is used for burning, development & events.",
    burnButton: "🔥 Burn 🎁",
    // DeFi Burn Card
    defiBurnName: "Burn/Donate",
    defiBurnDesc: "Donate $BANMAO to burn fund. Rank up!",
    defiBurnDetails: "Support community with $BANMAO. Leaderboard recorded.",
    defiBurnCommunityWallet: "Community Wallet",
    // GameFi Hub
    gamefiZone: "GameFi Zone",
    gamefiSubtitle: "Choose your game to start the adventure",
    gamefiBack: "Back",
    gamefiPlayNow: "Play Now",
    gamefiLive: "LIVE",
    gamefiComingSoon: "Coming Soon",
    gamefiMaintenance: "Maintenance",
    gamefiRpsName: "BANMAO RPS",
    gamefiRpsDesc: "On-chain Rock-Paper-Scissors PvP game on XLayer. Use $BANMAO tokens and challenge other players to win real crypto rewards!",
    gamefiSnakeName: "BANMAO SNAKE",
    gamefiSnakeDesc: "Classic Snake game with crypto rewards. Collect points, climb the leaderboard and earn rewards in $BANMAO tokens!",
    gamefiSlotsName: "BANMAO SLOTS",
    gamefiSlotsDesc: "Provably fair game! Spin to win up to 200x your entry plus progressive jackpot. Powered by on-chain randomness!",
    gamefiSlotsHowToPlay: "Place your entry, spin the reels! Match 3+ symbols to win. 5x Banmao = JACKPOT!",
    // Miner
    gamefiMinerName: "BANMAO MINER",
    gamefiMinerDesc: "Classic Gold Miner with crypto theme! Catch tokens and gems to earn points, then claim $BANMAO rewards on XLayer!",
    gamefiMinerDetails: "Catch tokens 🪙 and gems 💎 to earn points. Avoid rug pulls 💣! Reach the target score before time runs out, then claim your $BANMAO rewards!",
    gamefiMinerHowToPlay: "Click or tap to drop the hook. Catch valuable items to earn points. Reach target score before time runs out!",
    // FOMO
    gamefiFomoName: "BANMAO FOMO",
    gamefiFomoDesc: "Strategic last-attacker jackpot on XLayer! Pay 2,000 $BANMAO per attack to compete for the growing prize pool. The final attacker wins 75% of the jackpot, Top 10 attackers share 25%. 1% auto-burn on every attack!",
    gamefiFomoDetails: "Each attack costs 2,000 $BANMAO. Fund distribution: 75% Jackpot, 17% Dividends (shared among all attackers), 5% Seed Fund (next round), 2% Staking Rewards, 1% Auto-Burn. Dual-timer system: Soft Timer (6h, resets every attack) and Hard Timer (120h, decreases ~100 min per attack). When either timer hits zero, the last attacker wins 75% of the jackpot and Top 10 attackers share 25%. VIP tier system with reduced cooldown for frequent players. 2-hour claim window after round ends.",
    gamefiFomoHowToPlay: "Connect wallet → Approve $BANMAO → Attack (1-10x per tx, 2,000 tokens each). Each attack resets the 6h soft timer and shrinks the 120h hard timer. Be the last attacker when any timer expires to claim 75% of the jackpot! Attack more to rank in Top 10 and earn bonus rewards.",
    gamefiFooter: "Developed by ＤＯＲＥＭＯＮ",
    gamefiMoreGames: "More games coming soon!",
    gamefiLoadingGame: "Loading Game...",
    gamefiRpsHowToPlay: "Create or join a room, use your $BANMAO tokens, choose Rock/Paper/Scissors. Winner takes the pot!",
    gamefiSnakeHowToPlay: "Use arrow keys or swipe to control the snake. Collect coins & power-ups to increase your score and claim rewards!",
    gamefiAbout: "About",
    gamefiHowToPlay: "How to Play",
    gamefiSmartContract: "Smart Contract",
    gamefiViewExplorer: "View on Explorer",
    // Donor Modal
    totalDonated: "Total Donated",
    donationCount: "Donations",
    times: "times",
    loading: "Loading...",
    noData: "No data",
    editProfile: "Edit Profile",
    anonymous: "Anonymous",
    displayName: "Display Name",
    displayNamePlaceholder: "Enter your name...",
    topDonors: "Top Donors",
    // Browser Notice
    browserNoticeTitle: "🌐 Best Experience on Chrome",
    browserNoticeDesc: "GameFi works best on Google Chrome browser. Recommended for both PC and mobile devices.",
    browserNoticeMobile: "📱 Mobile tip: Increase your screen DPI/display density before playing for a better experience!",
    browserNoticeDesktop: "💻 Desktop: GameFi works perfectly on PC for the ultimate gaming experience!",
    browserNoticeDownload: "Download Chrome",
    browserNoticeInstalled: "Installed",
    browserNoticeClose: "Got it!",
    // Staking
    staking: "Staking",
    stakingTitle: "BANMAO STAKING",
    stakingSubtitle: "Lock your $BANMAO to earn rewards",
    stakingLock: "Lock Tokens",
    stakingUnlock: "Unlock",
    stakingRewards: "Claim Rewards",
    stakingAPY: "APY",
    stakingTotalLocked: "Total Locked",
    stakingYourStake: "Your Stake",
    stakingLockPeriod: "Lock Period",
    stakingDays: "days",
    stakingEarned: "Earned",
    stakingPending: "Pending Rewards",
    backToHub: "Back to DeFi Hub",
    // DeFi Hub
    defiHub: "DeFi Hub",
    defiExploreTitle: "Explore DeFi Services",
    defiExploreSubtitle: "Earn rewards, provide liquidity, and grow your $BANMAO holdings",
    defiDisabled: "DeFi Temporarily Disabled",
    defiDisabledDesc: "The DeFi feature is currently under maintenance. Please check back later.",
    defiBackHome: "Back to Home",
    defiTVL: "Total Value Locked",
    defiActiveUsers: "Active Users",
    defiBestAPY: "Best APY",
    defiServices: "Services",
    defiLive: "Live",
    defiComingSoon: "Coming Soon",
    defiEnter: "Enter",
    defiTvlTooltip: "Total amount of $BANMAO locked across all smart contracts.",
    defiStakersTooltip: "Total number of users participating in staking.",
    defiApyTooltip: "Annual Percentage Yield: Estimated yearly return rate.",
    defiBurnTooltip: "Total amount of $BANMAO permanently removed from supply.",
    // DeFi Services
    defiStakingName: "Staking",
    defiStakingDesc: "Lock $BANMAO, earn up to 75% APY",
    defiStakingDetails: "Maximize your returns by locking $BANMAO tokens. The longer you lock, the higher your reward multiplier (Share Booster). \n\nMechanisms:\n• Lock Period: Choose from flexible to 365 days.\n• Multiplier: Up to 2x shares for longer locks.\n• Penalty: Early unstaking incurs a fee that goes back to the reward pool.\n• Rewards: Paid in $BANMAO, claimable anytime.\n\nSmart Contract verifies all logic on-chain for complete transparency.",
    defiPoolsName: "Liquidity Pools",
    defiPoolsDesc: "Provide liquidity to earn trading fees and rewards",
    defiFarmingName: "Yield Farming",
    defiFarmingDesc: "Farm $BANMAO tokens by providing liquidity",
    defiLendingName: "Lending",
    defiLendingDesc: "Lend your assets to earn interest",
    defiAirdropName: "Airdrop",
    defiAirdropDesc: "Community tool to airdrop \$BANMAO to wallets that don't hold the token yet. Easier than sending one by one!",
    defiAirdropDetails: "A powerful community tool for \$BANMAO holders to distribute tokens to new wallets on XLayer in bulk. Scan for active wallets, exclude existing holders automatically, and send to hundreds of addresses in one session. Supports manual input, blockchain scanning, and CSV import with batch speeds up to x20.",
    // Staking Page UI
    stakingAmountToStake: "Amount to Stake",
    stakingAvailableBalance: "Available Balance",
    stakingSelectLockOption: "Selected Lock Option",
    stakingMultiplier: "Multiplier",
    stakingBoost: "Boost",
    stakingFlexible: "Flexible",
    stakingLockTokens: "Lock Tokens $BANMAO",
    stakingUnstakeTokens: "Unstake",
    stakingAmountToUnstake: "Amount to Unstake",
    stakingClaim: "Claim",
    stakingCompound: "Compound",
    stakingEmergencyWithdraw: "Emergency Withdraw",
    stakingRewardPool: "Reward Pool",
    stakingContractHealth: "Contract Health",
    stakingHealthy: "Healthy",
    stakingCheckRequired: "Check Required",
    stakingRewardsLeft: "Rewards left",
    stakingDonateTitle: "Donate to Reward Pool",
    stakingDonateDesc: "Support the community by donating tokens to the reward pool.",
    stakingDonateButton: "Donate",
    stakingApprove: "Approve",
    stakingDonateTip: "Donated tokens will be distributed to all stakers.",
    stakingDonateAction: "Donate",
    stakingDonateNote: "Support the project with $BANMAO tokens",
    stakingWaitWallet: "Waiting for wallet confirmation...",
    stakingTxPending: "Transaction pending...",
    stakingTxSuccess: "Transaction successful! ✅",
    stakingAvailableToUnstake: "Available to Unstake",
    stakingEstimatedEarnings: "Estimated Earnings",
    stakingStakeAmount: "Stake Amount",
    stakingEffectiveShares: "Effective Shares",
    stakingCalculatedNote: "Higher lock periods = More shares = Higher rewards",
    stakingTokensToReceive: "You will receive",
    stakingPenaltyWarning: "Early unstake penalty",
    // Panel Titles & Labels
    panelStats: "System Stats",
    panelStake: "Stake Tokens",
    panelUnstake: "Unstake Tokens",
    panelClaim: "Claim Rewards",
    panelCompound: "Compound",
    panelClose: "Close",
    // Panel Content
    balanceLabel: "Balance",
    stakedLabel: "Staked",
    amountToStake: "Amount to stake",
    amountToUnstake: "Amount to unstake",
    pendingRewards: "Pending Rewards",
    noRewardsMessage: "No pending rewards to claim.",
    autoCompoundDesc: "Auto-compound your rewards back into stake",
    confirmStake: "Confirm Stake",
    confirmUnstake: "Confirm Unstake",
    claimRewardsBtn: "Claim Rewards",
    compoundBtn: "Compound",
    approveToken: "Approve BANMAO",
    selectLockDuration: "Select Lock Duration",
    // Energy Sphere Display
    sphereRewardPool: "Reward Pool",
    sphereTVL: "TVL",
    sphereTotalShares: "Total Shares",
    sphereRewardRate: "Reward/day",
    sphereStatus: "Status",
    sphereHealthy: "Healthy",
    sphereUnhealthy: "Unhealthy",
    sphereTapToToggle: "Tap to toggle menu",
    // Stats Panel Extended
    statsTotalShares: "Total Shares",
    statsTotalSharesDesc: "The total number of shares in the staking pool. More shares = larger portion of rewards.",
    statsRewardRate: "Reward Rate",
    statsRewardRateDesc: "The amount of tokens distributed as rewards per day from the reward pool.",
    statsRewardRatePerSec: "Rate (Per Second)",
    statsRewardRatePerSecDesc: "The raw reward rate from contract in tokens per second (system-wide).",
    statsDaysLeft: "Days Left",
    statsDaysLeftDesc: "Estimated days until the reward pool is depleted based on current reward rate.",
    statsMinStake: "Min Stake",
    statsMinStakeDesc: "The minimum amount of tokens required to create a new stake position.",
    statsMaxStake: "Max Stake",
    statsMaxStakeDesc: "The maximum amount of tokens allowed per wallet for staking.",
    statsPenalty: "Early Penalty",
    statsPenaltyDesc: "Percentage penalty applied when unstaking before the lock period ends.",
    statsGracePeriod: "Grace Period",
    statsGracePeriodDesc: "Time window after lock ends during which you can unstake without penalty.",
    statsVipTier: "VIP Tier",
    statsVipTierDesc: "Your VIP status based on total staked amount. Higher tiers get bonus rewards.",
    statsPendingReward: "Pending Reward",
    statsPendingRewardDesc: "Your accumulated rewards waiting to be claimed or compounded.",
    statsTotalLockedDesc: "Total amount of tokens currently locked in the staking contract.",
    statsRewardPoolDesc: "Remaining tokens in the reward pool available for distribution.",
    statsYourStakeDesc: "Your personal staked amount across all active stake positions.",
    statsDays: "days",
    statsHours: "hours",
    statsClickForInfo: "Tap any stat for details",
    tooltipTapToClose: "Tap to close",
    // Common UI
    closeBtn: "Close",
    // Stats section headers
    stakingContractStats: "Contract Stats",
    stakingPersonalStats: "Your Stats",
    // Wallet balance
    walletBalance: "Wallet Balance",
    walletBalanceDesc: "Your current token balance available in your connected wallet for staking.",
    // Unstake Annotations
    unstakeEarlyTitle: "⚠️ Still Locked",
    unstakeEarlyDesc: "Lock period not yet ended.",
    unstakeGraceTitle: "⏰ Grace Period",
    unstakeGraceDesc: "Lock ended! Free unstake window active.",
    unstakeAfterTitle: "✅ Fully Unlocked",
    unstakeAfterDesc: "Unstake anytime with no penalty.",
    unstakePenaltyWarning: "Early unstake fee:",
    unstakeNoPenalty: "No penalty - Free to unstake!",
    unstakeLockRemaining: "Lock ends in:",
    unstakeGraceRemaining: "Grace ends in:",
    unstakeGracePeriodNote: "After lock ends, you have",
    unstakeGracePeriodNoteFree: "to unstake for free",
    unstakeLockEnded: "Lock ended",
    unstakeStatus: "Status",
    // Energy Sphere Refined
    spherePoolStats: "POOL STATS",
    sphereMyStats: "MY STATS",
    statsRateDaily: "Rate (Daily)",
    statsRatePerSec: "RATE/SEC",
    statsMyStake: "My Stake",
    statsPending: "Pending",
    // Orb Labels
    orbStats: "Stats",
    orbStake: "Stake",
    orbUnstake: "Unstake",
    orbClaim: "Claim",
    orbCompound: "Compound",
    // Sphere Hint
    tapSphereHint: "Tap Sphere to Open",
    // Claim History Panel
    claimHistoryTitle: "Claim Reward History",
    claimHistoryContract: "Staking Contract",
    claimHistoryAmount: "Amount",
    claimHistoryTime: "Time",
    claimHistoryViewTx: "View TX",
    claimHistoryNoRecords: "No claim history yet",
    claimHistoryLoading: "Loading claim history...",
    claimHistoryShowingRecords: "Showing {count} recent claim(s)",
    claimHistoryLoadError: "Unable to load history",
    claimHistorySearchExplorer: "Search on Explorer",
    claimHistoryJustNow: "Just now",
    claimHistoryMinutesAgo: "{n}m ago",
    claimHistoryHoursAgo: "{n}h ago",
    claimHistoryDaysAgo: "{n}d ago",
    claimHistoryExplorerGuide: "To find older history, search \"claimReward\" on Explorer",
    claimHistorySearchTip: "💡 Tip: Enter \"claimReward\" in the search box to find all claim transactions",
};
