// Indonesian translations
import type { LandingTranslations } from './index';

export const id: LandingTranslations = {
    logoTitle: "BANMAO NEBULA",
    tokenStats: "STATISTIK TOKEN",
    totalSupply: "TOTAL SUPLAI:",
    circulating: "Beredar",
    burned: "Dibakar",
    tokenDistribution: "Distribusi Token",
    holders: "PEMEGANG",
    globalHolders: "PEMEGANG GLOBAL",
    marketCap: "Kapitalisasi",
    liquidity: "Likuiditas",
    token: "Token",
    time: "Waktu",
    priceFeed: "HARGA TOKEN",
    network: "JARINGAN:",
    price: "HARGA:",
    change24h: "24JAM",
    mcap: "MCAP:",
    buyToken: "BELI $banmao",
    joinMission: "GABUNG MISI",
    gamefi: "GameFi",
    collection: "Koleksi",
    installApp: "INSTALL APLIKASI",
    installDesc: "Tambahkan ke layar utama!",
    installNow: "Install",
    howToInstall: "Cara Install",
    language: "BAHASA",
    selectLang: "Pilih Bahasa",
    settings: "PENGATURAN",
    theme: "TEMA",
    sound: "SUARA",
    minimizedApps: "APLIKASI DIMINIMALKAN",
    clickToRestore: "Klik untuk memulihkan",
    appsMinimized: "aplikasi diminimalkan",
    volume24h: "Volume 24J",
    transactions24h: "Transaksi 24J",
    totalTradeVolume: "$banmao Traded",
    community: "KOMUNITAS",
    joinUs: "Bergabung",
    dataVoid: "LUBANG HITAM",
    dataVoidWarning: "⚠️ Hapus SEMUA data?",
    dataVoidConfirm: "YA, HAPUS",
    dataVoidCancel: "BATAL",
    dataVoidCleared: "✓ Data dihapus!",
    tokenInfoTitle: "TENTANG BANMAO",
    tokenInfoDesc: "Banmao lahir dari perpaduan seru antara kucing 🐱 dan pisang 🍌. Nama ini memadukan bahasa Inggris dan Mandarin — \"Banana\" dan \"Māo (猫, kucing dalam bahasa Mandarin)\" — menciptakan Banmao, simbol humor, persatuan, dan kreativitas. Ini bukan sekadar nama, tetapi semangat menggabungkan Timur dan Barat, kesenangan dan makna, untuk membangun meme yang hidup.",
    totalBurned: "TOTAL TERBAKAR 🔥",
    burnHistory: "Lihat Riwayat & Donasi",
    burnDescription: "Riwayat bakar & donasi dompet komunitas. Semua $BANMAO digunakan untuk pembakaran, pengembangan & acara.",
    burnButton: "🔥 Bakar 🎁",
    defiBurnName: "Bakar/Donasi",
    defiBurnDesc: "Donasi $BANMAO ke dana. Naik peringkat!",
    defiBurnDetails: "Dukung komunitas dengan $BANMAO. Semua donasi tercatat di peringkat.",
    defiBurnCommunityWallet: "Dompet Komunitas",
    // GameFi Hub
    gamefiZone: "Zona GameFi",
    gamefiSubtitle: "Pilih game untuk memulai petualangan",
    gamefiBack: "Kembali",
    gamefiPlayNow: "Main Sekarang",
    gamefiLive: "AKTIF",
    gamefiComingSoon: "Segera Hadir",
    gamefiMaintenance: "Pemeliharaan",
    gamefiRpsName: "BANMAO Suit",
    gamefiRpsDesc: "Game PvP Suit on-chain di XLayer. Gunakan $BANMAO token dan tantang pemain lain untuk memenangkan hadiah kripto nyata!",
    gamefiSnakeName: "BANMAO Ular",
    gamefiSnakeDesc: "Game Ular klasik dengan hadiah kripto. Kumpulkan poin, naik peringkat dan dapatkan hadiah dalam $BANMAO token!",
    gamefiSlotsName: "BANMAO Putaran",
    gamefiSlotsDesc: "Permainan yang adil! Putar untuk menang hingga 200x partisipasi plus jackpot progresif. Ditenagai oleh randomness on-chain!",
    gamefiSlotsHowToPlay: "Mulai partisipasi, putar gulungan! Cocokkan 3+ simbol untuk menang. 5x Banmao = JACKPOT!",
    // Miner
    gamefiMinerName: "BANMAO Penambang",
    gamefiMinerDesc: "Game Gold Miner klasik dengan tema kripto! Tangkap token dan permata untuk poin, lalu klaim hadiah $BANMAO di XLayer!",
    gamefiMinerDetails: "Tangkap token🪙 dan permata💎 untuk mendapatkan poin. Hindari rug pull💣! Capai target skor sebelum waktu habis untuk mendapatkan $BANMAO!",
    gamefiMinerHowToPlay: "Klik untuk menjatuhkan kait. Tangkap item berharga untuk poin. Capai target skor sebelum waktu habis!",
    // FOMO
    gamefiFomoName: "BANMAO FOMO",
    gamefiFomoDesc: "Jackpot penyerang terakhir strategis di XLayer! Bayar 2.000 $BANMAO per serangan untuk bersaing memperebutkan hadiah yang terus bertambah. Penyerang terakhir menang 75% jackpot, Top 10 berbagi 25%. 1% auto-burn setiap serangan!",
    gamefiFomoDetails: "Setiap serangan biaya 2.000 $BANMAO. Distribusi dana: 75% Jackpot, 17% Dividen (dibagi semua penyerang), 5% Dana Bibit (ronde berikutnya), 2% Staking, 1% Auto-Burn. Sistem dual-timer: Timer Lunak (6 jam, reset setiap serangan) + Timer Keras (120 jam, berkurang ~100 menit per serangan). Ketika salah satu timer habis, penyerang terakhir menang 75% jackpot dan Top 10 berbagi 25%. Sistem VIP tier — semakin aktif, cooldown semakin singkat. Jendela klaim 2 jam setelah ronde berakhir.",
    gamefiFomoHowToPlay: "Hubungkan wallet → Setujui $BANMAO → Serang (1-10x per tx, 2.000 token tiap serangan). Setiap serangan me-reset timer lunak 6 jam dan memperpendek timer keras 120 jam. Jadilah penyerang terakhir saat timer habis untuk klaim 75% jackpot! Serang lebih banyak untuk masuk Top 10 dan dapatkan bonus.",
    gamefiWorldCupName: "BANMAO CUP",
    gamefiWorldCupDesc: "Stake $BANMAO untuk tim Piala Dunia favorit! APY dinamis berdasarkan hasil pertandingan. Tim menang dapat hadiah lebih, tim tersingkir dibekukan.",
    gamefiWorldCupDetails: "32 pool tim dengan pengali APY dinamis. Tim menang boost 1.5x APY, kalah turun 0.8x. Tim tersingkir dibekukan — tarik tanpa penalti. Pool juara dapat bonus 5x APY!",
    gamefiFooter: "Developed by ＤＯＲＥＭＯＮ",
    gamefiMoreGames: "Lebih banyak game segera hadir!",
    gamefiLoadingGame: "Memuat Game...",
    gamefiRpsHowToPlay: "Buat atau gabung room, gunakan $BANMAO token, pilih Batu/Gunting/Kertas. Pemenang mengambil semua!",
    gamefiSnakeHowToPlay: "Gunakan tombol panah atau geser untuk mengendalikan ular. Kumpulkan koin & power-up untuk meningkatkan skor dan klaim hadiah!",
    gamefiAbout: "Tentang",
    gamefiHowToPlay: "Cara Bermain",
    gamefiSmartContract: "Smart Contract",
    gamefiViewExplorer: "Lihat di Explorer",
    // Donor Modal
    totalDonated: "Total Donasi",
    donationCount: "Jumlah Donasi",
    times: "kali",
    loading: "Memuat...",
    noData: "Tidak ada data",
    editProfile: "Edit Profil",
    anonymous: "Anonim",
    displayName: "Nama Tampilan",
    displayNamePlaceholder: "Masukkan nama Anda...",
    topDonors: "Top Donatur",
    // Browser Notice
    browserNoticeTitle: "🌐 Pengalaman Terbaik di Chrome",
    browserNoticeDesc: "GameFi bekerja paling baik di browser Google Chrome. Disarankan untuk PC dan perangkat mobile.",
    browserNoticeMobile: "📱 Tips Mobile: Tingkatkan DPI/kepadatan tampilan layar sebelum bermain untuk pengalaman yang lebih baik!",
    browserNoticeDesktop: "💻 Desktop: GameFi bekerja sempurna di PC!",
    browserNoticeDownload: "Unduh Chrome",
    browserNoticeInstalled: "Terpasang",
    browserNoticeClose: "Mengerti!",
    // Staking
    staking: "Staking",
    stakingTitle: "BANMAO STAKING",
    stakingSubtitle: "Kunci $BANMAO untuk mendapatkan hadiah",
    stakingLock: "Kunci Token",
    stakingUnlock: "Buka Kunci",
    stakingRewards: "Klaim Hadiah",
    stakingAPY: "APY",
    stakingTotalLocked: "Total Terkunci",
    stakingYourStake: "Stake Anda",
    stakingLockPeriod: "Periode Kunci",
    stakingDays: "hari",
    stakingEarned: "Diperoleh",
    stakingPending: "Hadiah Tertunda",
    backToHub: "Kembali ke DeFi Hub",
    // DeFi Hub
    defiHub: "DeFi Hub",
    defiExploreTitle: "Jelajahi Layanan DeFi",
    defiExploreSubtitle: "Dapatkan hadiah, sediakan likuiditas, dan kembangkan $BANMAO Anda",
    defiDisabled: "DeFi Sementara Dinonaktifkan",
    defiDisabledDesc: "Fitur DeFi sedang dalam pemeliharaan. Silakan coba lagi nanti.",
    defiBackHome: "Kembali ke Beranda",
    defiTVL: "Total Nilai Terkunci",
    defiActiveUsers: "Pengguna Aktif",
    defiBestAPY: "APY Terbaik",
    defiServices: "Layanan",
    defiLive: "Aktif",
    defiComingSoon: "Segera Hadir",
    defiEnter: "Masuk",
    defiTvlTooltip: "Total $BANMAO yang terkunci di semua smart contract.",
    defiStakersTooltip: "Total pengguna yang berpartisipasi dalam staking.",
    defiApyTooltip: "Annual Percentage Yield: Estimasi tingkat pengembalian tahunan.",
    defiBurnTooltip: "Total $BANMAO yang dihapus secara permanen dari pasokan.",
    // DeFi Services
    defiStakingName: "Staking",
    defiStakingDesc: "Kunci $BANMAO, raih hadiah APY 75%",
    defiStakingDetails: "Maksimalkan keuntungan dengan mengunci token $BANMAO. Semakin lama dikunci, semakin tinggi pengganda hadiahnya.\n\nMekanisme:\n• Periode Kunci: Pilih dari fleksibel hingga 365 hari.\n• Pengganda: Hingga 2x saham untuk penguncian lama.\n• Penalti: Unstake awal dikenakan biaya yang kembali ke pool hadiah.\n• Hadiah: Dibayar dalam $BANMAO, dapat diklaim kapan saja.\n\nSmart Contract memverifikasi semua logika secara transparan di on-chain.",
    defiPoolsName: "Pool Likuiditas",
    defiPoolsDesc: "Sediakan likuiditas untuk mendapatkan biaya trading dan hadiah",
    defiFarmingName: "Yield Farming",
    defiFarmingDesc: "Farm $BANMAO token dengan menyediakan likuiditas",
    defiLendingName: "Pinjaman",
    defiLendingDesc: "Pinjamkan aset Anda untuk mendapatkan bunga",
    defiAirdropName: "Airdrop",
    defiAirdropDesc: "Distribusikan $BANMAO ke dompet aktif di XLayer",
    defiAirdropDetails: "Pindai XLayer untuk dompet aktif dan airdrop $BANMAO secara massal. Dompet yang sudah memiliki $BANMAO otomatis dikecualikan.",
    defiLaunchpadName: "Launchpad Memecoin",
    defiLaunchpadDesc: "Buat & perdagangkan memecoin dengan bonding curve. Otomatis lulus ke Uniswap V4.",
    defiLaunchpadDetails: "Luncurkan memecoin Anda sendiri dengan membayar biaya pembuatan dalam $BANMAO. Token diperdagangkan di bonding curve otomatis — tidak perlu pool likuiditas. Saat mencapai 500 OKB, likuiditas otomatis bermigrasi ke pool Uniswap V4 dengan Hook kustom. 50% biaya dibakar, 50% masuk kas komunitas.",
    // Staking Infographic Bullets
    defiStakingIntro: "Maksimalkan keuntungan dengan mengunci token $BANMAO. Semakin lama dikunci, semakin tinggi pengganda.",
    defiStakingBullet1Title: "Periode Kunci",
    defiStakingBullet1Desc: "Pilih dari fleksibel hingga 365 hari.",
    defiStakingBullet2Title: "Pengganda",
    defiStakingBullet2Desc: "Hingga 2x saham untuk penguncian lama.",
    defiStakingBullet3Title: "Penalti Awal",
    defiStakingBullet3Desc: "Biaya unstake awal kembali ke pool hadiah.",
    defiStakingBullet4Title: "Hadiah",
    defiStakingBullet4Desc: "Dibayar dalam $BANMAO, klaim kapan saja.",
    defiStakingOutro: "Smart Contract memverifikasi semua logika secara transparan di on-chain.",
    // Burn Infographic Bullets
    defiBurnIntro: "Dukung komunitas dengan mendonasikan token $BANMAO.",
    defiBurnBullet1Title: "Donasi",
    defiBurnBullet1Desc: "Kirim $BANMAO ke dompet komunitas.",
    defiBurnBullet2Title: "Peringkat",
    defiBurnBullet2Desc: "Semua donasi tercatat dan diperingkatkan.",
    defiBurnBullet3Title: "Dana Komunitas",
    defiBurnBullet3Desc: "Digunakan untuk bakar, pengembangan & acara.",
    defiBurnOutro: "Setiap token yang didonasikan memperkuat ekosistem Banmao.",
    // Airdrop Infographic Bullets
    defiAirdropIntro: "Distribusikan $BANMAO ke dompet baru di XLayer secara massal.",
    defiAirdropBullet1Title: "Pindai Dompet",
    defiAirdropBullet1Desc: "Temukan dompet aktif yang belum punya $BANMAO.",
    defiAirdropBullet2Title: "Kirim Massal",
    defiAirdropBullet2Desc: "Kirim ke ratusan alamat dalam satu sesi.",
    defiAirdropBullet3Title: "Multi-Impor",
    defiAirdropBullet3Desc: "Input manual, pindai blockchain, atau CSV.",
    defiAirdropOutro: "Mendukung kecepatan massal hingga x20.",
    // Staking Page UI
    stakingAmountToStake: "Jumlah Stake",
    stakingAvailableBalance: "Saldo Tersedia",
    stakingSelectLockOption: "Opsi Kunci Terpilih",
    stakingMultiplier: "Pengganda",
    stakingBoost: "Boost",
    stakingFlexible: "Fleksibel",
    stakingLockTokens: "Kunci Token $BANMAO",
    stakingUnstakeTokens: "Unstake",
    stakingAmountToUnstake: "Jumlah Unstake",
    stakingClaim: "Klaim",
    stakingCompound: "Gabung",
    stakingEmergencyWithdraw: "Penarikan Darurat",
    stakingRewardPool: "Pool Hadiah",
    stakingContractHealth: "Kesehatan Kontrak",
    stakingHealthy: "Sehat",
    stakingCheckRequired: "Perlu Diperiksa",
    stakingRewardsLeft: "Hadiah tersisa",
    stakingDonateTitle: "Donasi ke Pool Hadiah",
    stakingDonateDesc: "Dukung komunitas dengan mendonasikan token ke pool hadiah.",
    stakingDonateButton: "Donasi",
    stakingApprove: "Setujui",
    stakingDonateTip: "Token yang didonasikan akan didistribusikan ke semua staker.",
    stakingDonateAction: "Donasi",
    stakingDonateNote: "Dukung proyek dengan token $BANMAO",
    stakingWaitWallet: "Menunggu konfirmasi dompet...",
    stakingTxPending: "Transaksi tertunda...",
    stakingTxSuccess: "Transaksi berhasil! ✅",
    stakingAvailableToUnstake: "Tersedia untuk Unstake",
    stakingEstimatedEarnings: "Estimasi Penghasilan",
    stakingStakeAmount: "Jumlah Stake",
    stakingEffectiveShares: "Bagian Efektif",
    stakingCalculatedNote: "Periode kunci lebih lama = Lebih banyak bagian = Hadiah lebih tinggi",
    stakingTokensToReceive: "Anda akan menerima",
    stakingPenaltyWarning: "Penalti unstake dini",
    // Panel Titles & Labels
    panelStats: "Statistik Sistem",
    panelStake: "Stake Token",
    panelUnstake: "Unstake Token",
    panelClaim: "Klaim Hadiah",
    panelCompound: "Gabung",
    panelClose: "Tutup",
    // Panel Content
    balanceLabel: "Saldo",
    stakedLabel: "Di-stake",
    amountToStake: "Jumlah stake",
    amountToUnstake: "Jumlah unstake",
    pendingRewards: "Hadiah Tertunda",
    noRewardsMessage: "Tidak ada hadiah untuk diklaim.",
    autoCompoundDesc: "Otomatis gabungkan hadiah ke dalam stake",
    confirmStake: "Konfirmasi Stake",
    confirmUnstake: "Konfirmasi Unstake",
    claimRewardsBtn: "Klaim Hadiah",
    compoundBtn: "Gabung",
    approveToken: "Setujui BANMAO",
    selectLockDuration: "Pilih Durasi Kunci",
    // Energy Sphere Display
    sphereRewardPool: "Pool Hadiah",
    sphereTVL: "TVL",
    sphereTotalShares: "Total Saham",
    sphereRewardRate: "Hadiah/hari",
    sphereStatus: "Status",
    sphereHealthy: "Sehat",
    sphereUnhealthy: "Tidak Stabil",
    sphereTapToToggle: "Ketuk untuk menu",
    // Stats Panel Extended
    statsTotalShares: "Total Saham",
    statsTotalSharesDesc: "Jumlah total saham di pool staking. Lebih banyak saham = porsi hadiah lebih besar.",
    statsRewardRate: "Kecepatan Hadiah",
    statsRewardRateDesc: "Jumlah token yang didistribusikan sebagai hadiah per hari dari pool hadiah.",
    statsRewardRatePerSec: "Kecepatan (Per Detik)",
    statsRewardRatePerSecDesc: "Kecepatan hadiah mentah dari kontrak dalam token/detik (seluruh sistem).",
    statsDaysLeft: "Hari Tersisa",
    statsDaysLeftDesc: "Perkiraan hari hingga pool hadiah habis berdasarkan kecepatan saat ini.",
    statsMinStake: "Min Stake",
    statsMinStakeDesc: "Jumlah token minimum yang diperlukan untuk membuat posisi stake baru.",
    statsMaxStake: "Max Stake",
    statsMaxStakeDesc: "Jumlah token maksimum yang diizinkan per wallet untuk staking.",
    statsPenalty: "Penalti Awal",
    statsPenaltyDesc: "Persentase penalti yang berlaku saat unstake sebelum periode kunci berakhir.",
    statsGracePeriod: "Periode Tenggang",
    statsGracePeriodDesc: "Jangka waktu setelah kunci berakhir di mana Anda dapat unstake tanpa penalti.",
    statsVipTier: "Tingkat VIP",
    statsVipTierDesc: "Status VIP Anda berdasarkan total jumlah stake. Tingkat lebih tinggi = hadiah bonus.",
    statsPendingReward: "Hadiah Tertunda",
    statsPendingRewardDesc: "Hadiah akumulasi Anda yang menunggu untuk diklaim atau digabung.",
    statsTotalLockedDesc: "Total jumlah token yang saat ini terkunci dalam kontrak staking.",
    statsRewardPoolDesc: "Token tersisa di pool hadiah yang tersedia untuk distribusi.",
    statsYourStakeDesc: "Jumlah stake pribadi Anda di semua posisi stake aktif.",
    statsDays: "hari",
    statsHours: "jam",
    statsClickForInfo: "Ketuk statistik untuk detail",
    tooltipTapToClose: "Ketuk untuk menutup",
    // Common UI
    closeBtn: "Tutup",
    // Stats section headers
    stakingContractStats: "Statistik Kontrak",
    stakingPersonalStats: "Info Pribadi",
    // Wallet balance
    walletBalance: "Saldo Dompet",
    walletBalanceDesc: "Saldo token saat ini di dompet terhubung Anda yang tersedia untuk staking.",
    // Unstake Annotations
    unstakeEarlyTitle: "⚠️ Terkunci",
    unstakeEarlyDesc: "Periode kunci belum berakhir.",
    unstakeGraceTitle: "⏰ Masa Tenggang",
    unstakeGraceDesc: "Kunci selesai! Jendela pencairan gratis aktif.",
    unstakeAfterTitle: "✅ Sepenuhnya Terbuka",
    unstakeAfterDesc: "Cairkan kapan saja secara gratis.",
    unstakePenaltyWarning: "Biaya pencairan dini:",
    unstakeNoPenalty: "Gratis - Cairkan sekarang!",
    unstakeLockRemaining: "Kunci berakhir dalam:",
    unstakeGraceRemaining: "Masa tenggang tersisa:",
    unstakeGracePeriodNote: "Setelah kunci berakhir, Anda punya",
    unstakeGracePeriodNoteFree: "untuk pencairan gratis",
    unstakeLockEnded: "Kunci berakhir",
    unstakeStatus: "Status",
    // Energy Sphere Refined
    spherePoolStats: "STATISTIK POOL",
    sphereMyStats: "STATISTIK SAYA",
    statsRateDaily: "Kecepatan (Harian)",
    statsRatePerSec: "KECEPATAN/DET",
    statsMyStake: "Stake Saya",
    statsPending: "Tertunda",
    // Orb Labels
    orbStats: "Statistik",
    orbStake: "Stake",
    orbUnstake: "Unstake",
    orbClaim: "Klaim",
    orbCompound: "Gabung",
    // Sphere Hint
    tapSphereHint: "Ketuk Bola untuk Membuka",
    // Claim History Panel
    claimHistoryTitle: "Riwayat Klaim Hadiah",
    claimHistoryContract: "Kontrak Staking",
    claimHistoryAmount: "Jumlah",
    claimHistoryTime: "Waktu",
    claimHistoryViewTx: "Lihat TX",
    claimHistoryNoRecords: "Belum ada riwayat klaim",
    claimHistoryLoading: "Memuat riwayat...",
    claimHistoryShowingRecords: "Menampilkan {count} klaim terbaru",
    claimHistoryLoadError: "Gagal memuat riwayat",
    claimHistorySearchExplorer: "Cari di Explorer",
    claimHistoryJustNow: "Baru saja",
    claimHistoryMinutesAgo: "{n} menit lalu",
    claimHistoryHoursAgo: "{n} jam lalu",
    claimHistoryDaysAgo: "{n} hari lalu",
    claimHistoryExplorerGuide: "Untuk mencari riwayat lama, cari \"claimReward\" di Explorer",
    claimHistorySearchTip: "💡 Tips: Masukkan \"claimReward\" di kotak pencarian untuk melihat semua transaksi klaim",
};
