// Korean translations
import type { LandingTranslations } from './index';

export const ko: LandingTranslations = {
    logoTitle: "BANMAO 성운",
    tokenStats: "토큰 통계",
    totalSupply: "총 공급량:",
    circulating: "유통량",
    burned: "소각량",
    tokenDistribution: "토큰 배분",
    holders: "홀더",
    globalHolders: "글로벌 홀더",
    marketCap: "시가총액",
    liquidity: "유동성",
    token: "토큰",
    time: "시간",
    priceFeed: "가격 피드",
    network: "네트워크:",
    price: "가격:",
    change24h: "24시간",
    mcap: "시가총액:",
    buyToken: "$banmao 구매",
    joinMission: "미션 참가",
    gamefi: "GameFi",
    collection: "컬렉션",
    installApp: "앱 설치",
    installDesc: "홈 화면에 추가하여 빠르게 접속!",
    installNow: "설치하기",
    howToInstall: "설치 방법",
    language: "언어",
    selectLang: "언어 선택",
    settings: "설정",
    theme: "테마",
    sound: "소리",
    minimizedApps: "최소화된 앱",
    clickToRestore: "클릭하여 복원",
    appsMinimized: "개의 앱이 최소화됨",
    volume24h: "24H 거래량",
    transactions24h: "24H 거래",
    totalTradeVolume: "$banmao 거래량",
    community: "커뮤니티",
    joinUs: "참여하기",
    dataVoid: "데이터 블랙홀",
    dataVoidWarning: "⚠️ 모든 데이터 삭제?",
    dataVoidConfirm: "예, 삭제",
    dataVoidCancel: "취소",
    dataVoidCleared: "✓ 삭제됨!",
    tokenInfoTitle: "BANMAO 소개",
    tokenInfoDesc: "Banmao는 고양이 🐱와 바나나 🍌의 재미있는 결합에서 탄생했습니다. 이 이름은 영어와 중국어 — \"Banana\"와 \"Māo (猫, 중국어로 고양이)\"를 결합하여 — 유머, 통합, 창의성의 상징인 Banmao를 만들었습니다. 이것은 단순한 이름이 아니라, 동양과 서양, 재미와 의미를 결합하여 살아있는 밈을 만드는 정신입니다.",
    totalBurned: "총 소각량 🔥",
    burnHistory: "기록 및 기부 보기",
    burnDescription: "소각 기록 및 커뮤니티 지갑 기부. 모든 $BANMAO는 소각, 개발 및 이벤트에 사용됩니다.",
    burnButton: "🔥 소각 🎁",
    defiBurnName: "소각/기부",
    defiBurnDesc: "$BANMAO를 기부하고 리더보드에 오르세요!",
    defiBurnDetails: "$BANMAO 토큰을 기부하여 커뮤니티를 지원하세요. 리더보드 기록.",
    defiBurnCommunityWallet: "커뮤니티 지갑",
    // GameFi Hub
    gamefiZone: "GameFi 구역",
    gamefiSubtitle: "모험을 시작할 게임을 선택하세요",
    gamefiBack: "뒤로",
    gamefiPlayNow: "지금 플레이",
    gamefiLive: "라이브",
    gamefiComingSoon: "출시 예정",
    gamefiMaintenance: "점검 중",
    gamefiRpsName: "BANMAO 가위바위보",
    gamefiRpsDesc: "XLayer의 온체인 가위바위보 PvP 게임. $BANMAO 토큰을 사용하고 다른 플레이어와 대결하여 실제 크립토 보상을 받으세요!",
    gamefiSnakeName: "BANMAO 스네이크",
    gamefiSnakeDesc: "크립토 보상이 있는 클래식 스네이크 게임. 점수를 모으고, 리더보드에 오르며, $BANMAO 토큰으로 보상을 받으세요!",
    gamefiSlotsName: "BANMAO 스핀",
    gamefiSlotsDesc: "공정한 게임! 참여의 최대 200배 + 누적 잭팟을 획득하세요. 온체인 랜덤으로 구동!",
    gamefiSlotsHowToPlay: "참여하고 릴을 돌리세요! 3개 이상 일치하면 당첨. 5x Banmao = 잭팟!",
    // Miner
    gamefiMinerName: "BANMAO 광부",
    gamefiMinerDesc: "클래식 골드마이너 크립토 스타일! 토큰과 보석을 잡아 포인트를 얻고 XLayer에서 $BANMAO 보상을 받으세요!",
    gamefiMinerDetails: "토큰🪙과 보석💎을 잡아 포인트를 얻으세요. 러그풀💣을 피하세요! 시간 내에 목표 점수에 도달하면 $BANMAO를 받을 수 있습니다!",
    gamefiMinerHowToPlay: "클릭해서 갈고리를 내리세요. 가치 있는 아이템을 잡아 포인트를 얻으세요. 시간 내에 목표 점수를 달성하세요!",
    // FOMO
    gamefiFomoName: "BANMAO FOMO",
    gamefiFomoDesc: "XLayer의 전략적 마지막 공격자 잭팟! 공격당 2,000 $BANMAO를 지불하고 성장하는 상금 풀을 경쟁하세요. 마지막 공격자가 잭팟의 75%를 획득하고, Top 10 공격자가 25%를 나눕니다. 매 공격마다 1% 자동 소각!",
    gamefiFomoDetails: "공격당 2,000 $BANMAO 소비. 자금 분배: 75% 잭팟, 17% 배당금(모든 공격자 공유), 5% 시드 펀드(다음 라운드), 2% 스테이킹 보상, 1% 자동 소각. 듀얼 타이머: 소프트 타이머(6시간, 매 공격 시 리셋) + 하드 타이머(120시간, 공격당 약 100분 감소). 어느 타이머든 0이 되면 마지막 공격자가 잭팟 75%를, Top 10 공격자가 25%를 공유. VIP 등급 시스템 — 활발할수록 쿨다운 감소. 라운드 종료 후 2시간 수령 가능.",
    gamefiFomoHowToPlay: "지갑 연결 → $BANMAO 승인 → 공격(거래당 1-10회, 각 2,000 토큰). 매 공격은 6시간 소프트 타이머를 리셋하고 120시간 하드 타이머를 단축합니다. 타이머 만료 시 마지막 공격자가 되어 잭팟 75%를 획득하세요! 더 많이 공격하면 Top 10에 들어 추가 보상도 받을 수 있습니다.",
    gamefiFooter: "Developed by ＤＯＲＥＭＯＮ",
    gamefiMoreGames: "더 많은 게임이 곧 출시됩니다!",
    gamefiLoadingGame: "게임 로딩 중...",
    gamefiRpsHowToPlay: "방을 만들거나 참가하고, $BANMAO 토큰을 사용하고, 가위/바위/보를 선택하세요. 승자가 전부 가져갑니다!",
    gamefiSnakeHowToPlay: "화살표 키나 스와이프로 뱀을 조종하세요. 코인과 파워업을 수집하여 점수를 올리고 보상을 받으세요!",
    gamefiAbout: "소개",
    gamefiHowToPlay: "플레이 방법",
    gamefiSmartContract: "스마트 컨트랙트",
    gamefiViewExplorer: "Explorer에서 보기",
    // Donor Modal
    totalDonated: "총 기부액",
    donationCount: "기부 횟수",
    times: "회",
    loading: "로딩 중...",
    noData: "데이터 없음",
    editProfile: "프로필 편집",
    anonymous: "익명",
    displayName: "표시 이름",
    displayNamePlaceholder: "이름을 입력하세요...",
    topDonors: "최고 후원자",
    // Browser Notice
    browserNoticeTitle: "🌐 Chrome에서 최상의 경험",
    browserNoticeDesc: "GameFi는 Google Chrome 브라우저에서 가장 잘 작동합니다. PC와 모바일 모두에서 권장됩니다.",
    browserNoticeMobile: "📱 모바일 팁: 게임 전에 화면 DPI/디스플레이 밀도를 높이면 더 나은 경험을 할 수 있습니다!",
    browserNoticeDesktop: "💻 데스크톱: PC에서 GameFi가 완벽하게 작동합니다!",
    browserNoticeDownload: "Chrome 다운로드",
    browserNoticeInstalled: "설치됨",
    browserNoticeClose: "알겠습니다!",
    // Staking
    staking: "Staking",
    stakingTitle: "BANMAO 스테이킹",
    stakingSubtitle: "$BANMAO를 잠그고 보상을 받으세요",
    stakingLock: "토큰 잠금",
    stakingUnlock: "잠금 해제",
    stakingRewards: "보상 받기",
    stakingAPY: "APY",
    stakingTotalLocked: "총 잠금량",
    stakingYourStake: "나의 스테이크",
    stakingLockPeriod: "잠금 기간",
    stakingDays: "일",
    stakingEarned: "획득",
    stakingPending: "보상 대기 중",
    backToHub: "DeFi Hub로 돌아가기",
    // DeFi Hub
    defiHub: "DeFi 허브",
    defiExploreTitle: "DeFi 서비스 탐색",
    defiExploreSubtitle: "보상을 받고, 유동성을 제공하고, $BANMAO 보유량을 늘리세요",
    defiDisabled: "DeFi 일시 중지",
    defiDisabledDesc: "DeFi 기능이 현재 점검 중입니다. 나중에 다시 확인해 주세요.",
    defiBackHome: "홈으로 돌아가기",
    defiTVL: "총 잠금 가치",
    defiActiveUsers: "활성 사용자",
    defiBestAPY: "최고 APY",
    defiServices: "서비스",
    defiLive: "라이브",
    defiComingSoon: "출시 예정",
    defiEnter: "입장",
    defiTvlTooltip: "모든 스마트 컨트랙트에 락업된 $BANMAO의 총 가치입니다.",
    defiStakersTooltip: "스테이킹에 참여하고 있는 총 사용자 수입니다.",
    defiApyTooltip: "연간 예상 수익률(APY)입니다.",
    defiBurnTooltip: "유통량에서 영구적으로 소각된 $BANMAO의 총량입니다.",
    // DeFi Services
    defiStakingName: "스테이킹",
    defiStakingDesc: "$BANMAO 잠금, 최대 75% APY 보상",
    defiStakingDetails: "$BANMAO 토큰을 잠궈 수익을 극대화하세요. 오래 잠글수록 보상 배수(Share Booster)가 높아집니다.\n\n작동 방식:\n• 잠금 기간: 유동적 기간부터 365일까지 선택 가능.\n• 배수: 장기 잠금 시 최대 2배 지분 획득.\n• 페널티: 조기 출금 시 수수료가 부과되며, 이는 보상 풀로 반환됩니다.\n• 보상: $BANMAO로 지급되며 언제든지 청구 가능.\n\n스마트 계약이 체인 상에서 모든 로직을 투명하게 검증합니다.",
    defiPoolsName: "유동성 풀",
    defiPoolsDesc: "유동성을 제공하여 거래 수수료와 보상을 받으세요",
    defiFarmingName: "이자 농사",
    defiFarmingDesc: "유동성을 제공하여 $BANMAO 토큰을 채굴하세요",
    defiLendingName: "대출",
    defiLendingDesc: "자산을 대출하여 이자를 받으세요",
    defiAirdropName: "에어드랍",
    defiAirdropDesc: "XLayer 활성 지갑에 $BANMAO 배포",
    defiAirdropDetails: "XLayer 활성 지갑을 스캔하고 $BANMAO를 대량 에어드랍합니다. 이미 보유한 지갑은 자동 제외.",
    // Staking Page UI
    stakingAmountToStake: "스테이킹 금액",
    stakingAvailableBalance: "사용 가능 잔액",
    stakingSelectLockOption: "선택된 잠금 옵션",
    stakingMultiplier: "승수",
    stakingBoost: "부스트",
    stakingFlexible: "유연",
    stakingLockTokens: "$BANMAO 토큰 잠금",
    stakingUnstakeTokens: "언스테이크",
    stakingAmountToUnstake: "언스테이크 금액",
    stakingClaim: "청구",
    stakingCompound: "복리",
    stakingEmergencyWithdraw: "긴급 출금",
    stakingRewardPool: "보상 풀",
    stakingContractHealth: "컨트랙트 상태",
    stakingHealthy: "정상",
    stakingCheckRequired: "확인 필요",
    stakingRewardsLeft: "남은 보상",
    stakingDonateTitle: "보상 풀에 기부",
    stakingDonateDesc: "보상 풀에 토큰을 기부하여 커뮤니티를 지원하세요.",
    stakingDonateButton: "기부",
    stakingApprove: "승인",
    stakingDonateTip: "기부된 토큰은 모든 스테이커에게 분배됩니다.",
    stakingDonateAction: "기부",
    stakingDonateNote: "$BANMAO 토큰으로 프로젝트 지원",
    stakingWaitWallet: "지갑 확인 대기 중...",
    stakingTxPending: "트랜잭션 대기 중...",
    stakingTxSuccess: "트랜잭션 성공! ✅",
    stakingAvailableToUnstake: "출금 가능 잔액",
    stakingEstimatedEarnings: "예상 수익",
    stakingStakeAmount: "스테이킹 금액",
    stakingEffectiveShares: "유효 지분",
    stakingCalculatedNote: "잠금 기간이 길수록 = 지분이 많아짐 = 보상이 높아짐",
    stakingTokensToReceive: "수령 예정 금액",
    stakingPenaltyWarning: "조기 출금 수수료",
    // Panel Titles & Labels
    panelStats: "시스템 통계",
    panelStake: "토큰 스테이킹",
    panelUnstake: "언스테이킹",
    panelClaim: "보상 받기",
    panelCompound: "복리",
    panelClose: "닫기",
    // Panel Content
    balanceLabel: "잔액",
    stakedLabel: "스테이킹 됨",
    amountToStake: "스테이킹 금액",
    amountToUnstake: "언스테이킹 금액",
    pendingRewards: "대기 중인 보상",
    noRewardsMessage: "받을 보상이 없습니다.",
    autoCompoundDesc: "보상을 스테이킹에 자동 복리 적용",
    confirmStake: "스테이킹 확인",
    confirmUnstake: "언스테이킹 확인",
    claimRewardsBtn: "보상 받기",
    compoundBtn: "복리",
    approveToken: "BANMAO 승인",
    selectLockDuration: "잠금 기간 선택",
    // Energy Sphere Display
    sphereRewardPool: "보상 풀",
    sphereTVL: "TVL",
    sphereTotalShares: "총 지분",
    sphereRewardRate: "보상/일",
    sphereStatus: "상태",
    sphereHealthy: "정상",
    sphereUnhealthy: "불안정",
    sphereTapToToggle: "탭하여 메뉴 전환",
    // Stats Panel Extended
    statsTotalShares: "총 지분",
    statsTotalSharesDesc: "스테이킹 풀의 총 지분 수. 지분이 많을수록 = 보상 비율이 높아집니다.",
    statsRewardRate: "보상 속도",
    statsRewardRateDesc: "보상 풀에서 하루에 분배되는 토큰 양.",
    statsRewardRatePerSec: "속도 (초당)",
    statsRewardRatePerSecDesc: "계약의 원시 보상 속도 (토큰/초, 시스템 전체).",
    statsDaysLeft: "남은 일수",
    statsDaysLeftDesc: "현재 보상 속도 기준으로 보상 풀이 소진될 때까지 예상 일수.",
    statsMinStake: "최소 스테이크",
    statsMinStakeDesc: "새 스테이크 포지션을 만들기 위한 최소 토큰 수량.",
    statsMaxStake: "최대 스테이크",
    statsMaxStakeDesc: "지갑당 스테이킹 가능한 최대 토큰 양.",
    statsPenalty: "조기 출금 패널티",
    statsPenaltyDesc: "잠금 기간 종료 전 언스테이킹 시 적용되는 패널티 비율.",
    statsGracePeriod: "유예 기간",
    statsGracePeriodDesc: "잠금 종료 후 패널티 없이 언스테이킹할 수 있는 기간.",
    statsVipTier: "VIP 등급",
    statsVipTierDesc: "총 스테이킹 금액 기반 VIP 상태. 높은 등급 = 보너스 보상.",
    statsPendingReward: "대기 중 보상",
    statsPendingRewardDesc: "청구 또는 복리 적용 대기 중인 누적 보상.",
    statsTotalLockedDesc: "현재 스테이킹 계약에 잠긴 총 토큰 양.",
    statsRewardPoolDesc: "분배 가능한 보상 풀의 남은 토큰.",
    statsYourStakeDesc: "모든 활성 스테이크 포지션에서의 개인 스테이킹 금액.",
    statsDays: "일",
    statsHours: "시간",
    statsClickForInfo: "통계를 탭하여 상세 정보 보기",
    tooltipTapToClose: "닫으려면 탭하세요",
    // Common UI
    closeBtn: "닫기",
    // Stats section headers
    stakingContractStats: "컨트랙트 통계",
    stakingPersonalStats: "내 정보",
    // Wallet balance
    walletBalance: "지갑 잔액",
    walletBalanceDesc: "스테이킹에 사용할 수 있는 연결된 지갑의 현재 토큰 잔액입니다.",
    // Unstake Annotations
    unstakeEarlyTitle: "⚠️ 잠금 중",
    unstakeEarlyDesc: "잠금 기간이 아직 종료되지 않았습니다.",
    unstakeGraceTitle: "⏰ 유예 기간",
    unstakeGraceDesc: "잠금 종료! 무료 언스테이킹 창이 활성화되었습니다.",
    unstakeAfterTitle: "✅ 완전 해제됨",
    unstakeAfterDesc: "언제든 무료로 언스테이킹 가능.",
    unstakePenaltyWarning: "조기 언스테이킹 수수료:",
    unstakeNoPenalty: "무료 - 지금 언스테이킹!",
    unstakeLockRemaining: "잠금 만료:",
    unstakeGraceRemaining: "유예 기간 남음:",
    unstakeGracePeriodNote: "잠금 종료 후",
    unstakeGracePeriodNoteFree: "무료로 언스테이킹",
    unstakeLockEnded: "잠금 종료",
    unstakeStatus: "상태",
    // Energy Sphere Refined
    spherePoolStats: "풀 통계",
    sphereMyStats: "내 통계",
    statsRateDaily: "속도 (일일)",
    statsRatePerSec: "속도/초",
    statsMyStake: "내 스테이크",
    statsPending: "대기 중",
    // Orb Labels
    orbStats: "통계",
    orbStake: "스테이크",
    orbUnstake: "언스테이크",
    orbClaim: "받기",
    orbCompound: "복리",
    // Sphere Hint
    tapSphereHint: "구체를 탭하여 열기",
    // Claim History Panel
    claimHistoryTitle: "보상 청구 기록",
    claimHistoryContract: "스테이킹 계약",
    claimHistoryAmount: "수량",
    claimHistoryTime: "시간",
    claimHistoryViewTx: "TX 보기",
    claimHistoryNoRecords: "청구 기록이 없습니다",
    claimHistoryLoading: "기록 로딩 중...",
    claimHistoryShowingRecords: "최근 {count}건 표시",
    claimHistoryLoadError: "기록을 불러올 수 없습니다",
    claimHistorySearchExplorer: "Explorer에서 검색",
    claimHistoryJustNow: "방금",
    claimHistoryMinutesAgo: "{n}분 전",
    claimHistoryHoursAgo: "{n}시간 전",
    claimHistoryDaysAgo: "{n}일 전",
    claimHistoryExplorerGuide: "이전 기록을 찾으려면 Explorer에서 \"claimReward\"를 검색하세요",
    claimHistorySearchTip: "💡 팁: 검색창에 \"claimReward\"를 입력하여 모든 청구 거래를 확인하세요",
};
