// Russian translations
import type { LandingTranslations } from './index';

export const ru: LandingTranslations = {
    logoTitle: "BANMAO ТУМАННОСТЬ",
    tokenStats: "СТАТИСТИКА ТОКЕНА",
    totalSupply: "ОБЩИЙ ЗАПАС:",
    circulating: "В обращении",
    burned: "Сожжено",
    tokenDistribution: "Распределение токенов",
    holders: "ДЕРЖАТЕЛИ",
    globalHolders: "ГЛОБАЛЬНЫЕ ДЕРЖАТЕЛИ",
    marketCap: "Капитализация",
    liquidity: "Ликвидность",
    token: "Токен",
    time: "Время",
    priceFeed: "КУРС ТОКЕНА",
    network: "СЕТЬ:",
    price: "ЦЕНА:",
    change24h: "24Ч",
    mcap: "КАПИТАЛИЗАЦИЯ:",
    buyToken: "КУПИТЬ $banmao",
    joinMission: "ПРИСОЕДИНИТЬСЯ",
    gamefi: "GameFi",
    collection: "Коллекция",
    installApp: "УСТАНОВИТЬ",
    installDesc: "Добавьте на главный экран!",
    installNow: "Установить",
    howToInstall: "Как установить",
    language: "ЯЗЫК",
    selectLang: "Выбрать язык",
    settings: "НАСТРОЙКИ",
    theme: "ТЕМА",
    sound: "ЗВУК",
    minimizedApps: "СВЁРНУТЫЕ ПРИЛОЖЕНИЯ",
    clickToRestore: "Нажмите для восстановления",
    appsMinimized: "приложений свёрнуто",
    volume24h: "Объём 24ч",
    transactions24h: "Сделок 24ч",
    totalTradeVolume: "$banmao торг.",
    community: "СООБЩЕСТВО",
    joinUs: "Присоединяйтесь",
    dataVoid: "ЧЁРНАЯ ДЫРА",
    dataVoidWarning: "⚠️ Удалить ВСЕ данные?",
    dataVoidConfirm: "ДА, СБРОС",
    dataVoidCancel: "ОТМЕНА",
    dataVoidCleared: "✓ Данные удалены!",
    tokenInfoTitle: "О BANMAO",
    tokenInfoDesc: "Banmao родился из игривого слияния кота 🐱 и банана 🍌. Название сочетает английский и китайский — \"Banana\" и \"Māo (猫, кот по-китайски)\" — создавая Banmao, символ юмора, единства и креативности. Это не просто имя, а дух объединения Востока и Запада, веселья и смысла, для создания живого мема.",
    totalBurned: "ВСЕГО СОЖЖЕНО 🔥",
    burnHistory: "История и пожертвования",
    burnDescription: "История сжигания и донаты в кошелёк сообщества. Все $BANMAO используются для сжигания, разработки и мероприятий.",
    burnButton: "🔥 Сжечь 🎁",
    defiBurnName: "Сжечь/Донат",
    defiBurnDesc: "Пожертвуйте $BANMAO в фонд. Рейтинг и признание!",
    defiBurnDetails: "Поддержите сообщество $BANMAO. Донаты записываются в рейтинг.",
    defiBurnCommunityWallet: "Кошелёк сообщества",
    // GameFi Hub
    gamefiZone: "Зона GameFi",
    gamefiSubtitle: "Выберите игру, чтобы начать приключение",
    gamefiBack: "Назад",
    gamefiPlayNow: "Играть",
    gamefiLive: "ОНЛАЙН",
    gamefiComingSoon: "Скоро",
    gamefiMaintenance: "Тех. работы",
    gamefiRpsName: "BANMAO Камень-Ножницы-Бумага",
    gamefiRpsDesc: "Онлайн PvP игра Камень-Ножницы-Бумага на XLayer. Используйте $BANMAO токены и бросайте вызов другим игрокам за реальные крипто награды!",
    gamefiSnakeName: "BANMAO Змейка",
    gamefiSnakeDesc: "Классическая игра Змейка с крипто наградами. Собирайте очки, поднимайтесь в рейтинге и получайте награды в $BANMAO токенах!",
    gamefiSlotsName: "BANMAO Спины",
    gamefiSlotsDesc: "Честная игра! Выигрывайте до 200x участия плюс прогрессивный джекпот. На базе ончейн рандома!",
    gamefiSlotsHowToPlay: "Внесите участие, крутите барабаны! 3+ совпадения = выигрыш. 5x Banmao = ДЖЕКПОТ!",
    // Miner
    gamefiMinerName: "BANMAO Шахтёр",
    gamefiMinerDesc: "Классический Gold Miner в крипто стиле! Ловите токены и самоцветы, зарабатывайте очки и получайте $BANMAO на XLayer!",
    gamefiMinerDetails: "Ловите токены🪙 и самоцветы💎, чтобы заработать очки. Избегайте rug pull💣! Достигните цели до конца времени, чтобы получить $BANMAO!",
    gamefiMinerHowToPlay: "Нажмите, чтобы опустить крюк. Ловите ценные предметы для очков. Достигните цели до конца времени!",
    // FOMO
    gamefiFomoName: "BANMAO FOMO",
    gamefiFomoDesc: "Стратегический джекпот последнего атакующего на XLayer! Платите 2,000 $BANMAO за атаку и боритесь за растущий призовой фонд. Последний атакующий получает 75% джекпота, Топ-10 делят 25%. 1% автосжигание с каждой атаки!",
    gamefiFomoDetails: "Каждая атака стоит 2,000 $BANMAO. Распределение: 75% Джекпот, 17% Дивиденды (между всеми атакующими), 5% Сид-фонд (следующий раунд), 2% Стейкинг, 1% Авто-сжигание. Двойной таймер: Мягкий (6ч, сброс при каждой атаке) + Жёсткий (120ч, уменьшается ~100 мин за атаку). Когда любой таймер достигнет нуля, последний атакующий получает 75% джекпота, Топ-10 делят 25%. VIP уровни — чем активнее, тем короче кулдаун. 2-часовое окно для получения приза.",
    gamefiFomoHowToPlay: "Подключите кошелёк → Одобрите $BANMAO → Атакуйте (1-10x за транзакцию, 2,000 токенов каждая). Каждая атака сбрасывает 6ч мягкий таймер и сокращает 120ч жёсткий таймер. Станьте последним атакующим при истечении таймера и получите 75% джекпота! Атакуйте больше, чтобы попасть в Топ-10 и получить бонус.",
    gamefiWorldCupName: "BANMAO CUP",
    gamefiWorldCupDesc: "Стейкайте $BANMAO за любимую сборную! Динамический APY по результатам матчей. Победители получают больше, проигравшие заморожены.",
    gamefiWorldCupDetails: "32 пула команд с динамическим множителем APY. Победа — буст 1.5x, поражение — снижение 0.8x. Вылетевшие замораживаются — вывод без штрафа. Пул чемпиона получает 5x APY бонус!",
    gamefiFooter: "Developed by ＤＯＲＥＭＯＮ",
    gamefiMoreGames: "Скоро больше игр!",
    gamefiLoadingGame: "Загрузка игры...",
    gamefiRpsHowToPlay: "Создайте или присоединитесь к комнате, используйте $BANMAO, выберите Камень/Ножницы/Бумагу. Победитель забирает все!",
    gamefiSnakeHowToPlay: "Используйте стрелки или свайп для управления змейкой. Собирайте монеты и бонусы для увеличения очков и получения наград!",
    gamefiAbout: "О игре",
    gamefiHowToPlay: "Как играть",
    gamefiSmartContract: "Смарт-контракт",
    gamefiViewExplorer: "Смотреть в Explorer",
    // Donor Modal
    totalDonated: "Всего пожертвовано",
    donationCount: "Количество пожертвований",
    times: "раз",
    loading: "Загрузка...",
    noData: "Нет данных",
    editProfile: "Редактировать профиль",
    anonymous: "Аноним",
    displayName: "Отображаемое имя",
    displayNamePlaceholder: "Введите ваше имя...",
    topDonors: "Топ Спонсоры",
    // Browser Notice
    browserNoticeTitle: "🌐 Лучший опыт в Chrome",
    browserNoticeDesc: "GameFi лучше всего работает в браузере Google Chrome. Рекомендуется для ПК и мобильных устройств.",
    browserNoticeMobile: "📱 Совет для мобильных: Увеличьте DPI/плотность дисплея экрана перед игрой для лучшего опыта!",
    browserNoticeDesktop: "💻 ПК: GameFi работает идеально на компьютере!",
    browserNoticeDownload: "Скачать Chrome",
    browserNoticeInstalled: "Установлен",
    browserNoticeClose: "Понятно!",
    // Staking
    staking: "Staking",
    stakingTitle: "BANMAO СТЕЙКИНГ",
    stakingSubtitle: "Заблокируйте $BANMAO для получения наград",
    stakingLock: "Заблокировать токены",
    stakingUnlock: "Разблокировать",
    stakingRewards: "Получить награды",
    stakingAPY: "APY",
    stakingTotalLocked: "Всего заблокировано",
    stakingYourStake: "Ваш стейк",
    stakingLockPeriod: "Период блокировки",
    stakingDays: "дней",
    stakingEarned: "Заработано",
    stakingPending: "Ожидаемые награды",
    backToHub: "Назад в DeFi Hub",
    // DeFi Hub
    defiHub: "DeFi Хаб",
    defiExploreTitle: "Исследуйте DeFi сервисы",
    defiExploreSubtitle: "Зарабатывайте награды, предоставляйте ликвидность и увеличивайте свои $BANMAO",
    defiDisabled: "DeFi временно недоступен",
    defiDisabledDesc: "Функция DeFi находится на техобслуживании. Пожалуйста, зайдите позже.",
    defiBackHome: "На главную",
    defiTVL: "Заблокировано",
    defiActiveUsers: "Активных пользователей",
    defiBestAPY: "Лучший APY",
    defiServices: "Сервисы",
    defiLive: "Онлайн",
    defiComingSoon: "Скоро",
    defiEnter: "Войти",
    defiTvlTooltip: "Общая сумма $BANMAO, заблокированная во всех смарт-контрактах.",
    defiStakersTooltip: "Общее количество пользователей, участвующих в стейкинге.",
    defiApyTooltip: "Годовая процентная доходность: ожидаемая прибыль за год.",
    defiBurnTooltip: "Общая сумма $BANMAO, навсегда изъятая из обращения.",
    // DeFi Services
    defiStakingName: "Стейкинг",
    defiStakingDesc: "Заблокируйте $BANMAO, APY до 75%",
    defiStakingDetails: "Увеличьте прибыль, заблокировав токены $BANMAO. Чем дольше срок, тем выше множитель наград.\n\nМеханизмы:\n• Срок: От гибкого до 365 дней.\n• Множитель: До 2x акций для долгих сроков.\n• Штраф: Ранний вывод имеет комиссию, возвращаемую в пул.\n• Награды: В $BANMAO, можно забрать в любое время.\n\nСмарт-контракт гарантирует прозрачность всех операций.",
    defiPoolsName: "Пулы ликвидности",
    defiPoolsDesc: "Предоставляйте ликвидность и зарабатывайте на комиссиях",
    defiFarmingName: "Фермерство",
    defiFarmingDesc: "Фармите $BANMAO токены предоставляя ликвидность",
    defiLendingName: "Кредитование",
    defiLendingDesc: "Давайте активы в долг и получайте проценты",
    defiAirdropName: "Аирдроп",
    defiAirdropDesc: "Раздать $BANMAO активным кошелькам XLayer",
    defiAirdropDetails: "Сканируйте XLayer для поиска активных кошельков и раздайте $BANMAO массово. Кошельки с $BANMAO автоматически исключаются.",
    // Staking Infographic Bullets
    defiStakingIntro: "Увеличьте прибыль, заблокировав токены $BANMAO. Чем дольше — тем выше множитель.",
    defiStakingBullet1Title: "Период блокировки",
    defiStakingBullet1Desc: "От гибкого до 365 дней.",
    defiStakingBullet2Title: "Множитель",
    defiStakingBullet2Desc: "До 2x акций для долгих сроков.",
    defiStakingBullet3Title: "Штраф за вывод",
    defiStakingBullet3Desc: "Комиссия возвращается в пул наград.",
    defiStakingBullet4Title: "Награды",
    defiStakingBullet4Desc: "Выплата в $BANMAO, получение в любое время.",
    defiStakingOutro: "Смарт-контракт гарантирует прозрачность всех операций.",
    // Burn Infographic Bullets
    defiBurnIntro: "Поддержите сообщество, пожертвовав $BANMAO.",
    defiBurnBullet1Title: "Пожертвовать",
    defiBurnBullet1Desc: "Отправьте $BANMAO в кошелёк сообщества.",
    defiBurnBullet2Title: "Рейтинг",
    defiBurnBullet2Desc: "Все пожертвования записываются в рейтинг.",
    defiBurnBullet3Title: "Фонд сообщества",
    defiBurnBullet3Desc: "Для сжигания, разработки и мероприятий.",
    defiBurnOutro: "Каждый пожертвованный токен укрепляет экосистему Banmao.",
    // Airdrop Infographic Bullets
    defiAirdropIntro: "Массовая раздача $BANMAO новым кошелькам на XLayer.",
    defiAirdropBullet1Title: "Сканирование",
    defiAirdropBullet1Desc: "Поиск активных кошельков без $BANMAO.",
    defiAirdropBullet2Title: "Массовая отправка",
    defiAirdropBullet2Desc: "Отправка на сотни адресов за одну сессию.",
    defiAirdropBullet3Title: "Мульти-импорт",
    defiAirdropBullet3Desc: "Ручной ввод, сканирование или CSV.",
    defiAirdropOutro: "Поддержка скорости до x20 для максимальной эффективности.",
    // Staking Page UI
    stakingAmountToStake: "Сумма для стейкинга",
    stakingAvailableBalance: "Доступный баланс",
    stakingSelectLockOption: "Выбранный период блокировки",
    stakingMultiplier: "Множитель",
    stakingBoost: "Буст",
    stakingFlexible: "Гибкий",
    stakingLockTokens: "Заблокировать $BANMAO",
    stakingUnstakeTokens: "Разблокировать",
    stakingAmountToUnstake: "Сумма для разблокировки",
    stakingClaim: "Получить",
    stakingCompound: "Реинвестировать",
    stakingEmergencyWithdraw: "Экстренный вывод",
    stakingRewardPool: "Пул наград",
    stakingContractHealth: "Состояние контракта",
    stakingHealthy: "Здоров",
    stakingCheckRequired: "Требуется проверка",
    stakingRewardsLeft: "Осталось наград",
    stakingDonateTitle: "Пожертвовать в пул наград",
    stakingDonateDesc: "Поддержите сообщество, пожертвовав токены в пул наград.",
    stakingDonateButton: "Пожертвовать",
    stakingApprove: "Одобрить",
    stakingDonateTip: "Пожертвованные токены будут распределены между всеми стейкерами.",
    stakingDonateAction: "Пожертвовать",
    stakingDonateNote: "Поддержите проект токенами $BANMAO",
    stakingWaitWallet: "Ожидание подтверждения кошелька...",
    stakingTxPending: "Транзакция в обработке...",
    stakingTxSuccess: "Транзакция успешна! ✅",
    stakingAvailableToUnstake: "Доступно для снятия",
    stakingEstimatedEarnings: "Ожидаемый доход",
    stakingStakeAmount: "Сумма стейкинга",
    stakingEffectiveShares: "Фактическая доля",
    stakingCalculatedNote: "Дольше период блокировки = Больше доля = Выше награды",
    stakingTokensToReceive: "Вы получите",
    stakingPenaltyWarning: "Штраф за досрочный вывод",
    // Panel Titles & Labels
    panelStats: "Статистика системы",
    panelStake: "Стейкинг токенов",
    panelUnstake: "Вывод токенов",
    panelClaim: "Получить награды",
    panelCompound: "Реинвестировать",
    panelClose: "Закрыть",
    // Panel Content
    balanceLabel: "Баланс",
    stakedLabel: "На стейке",
    amountToStake: "Сумма для стейка",
    amountToUnstake: "Сумма для вывода",
    pendingRewards: "Ожидаемые награды",
    noRewardsMessage: "Нет наград для получения.",
    autoCompoundDesc: "Автоматически реинвестировать награды в стейк",
    confirmStake: "Подтвердить стейк",
    confirmUnstake: "Подтвердить вывод",
    claimRewardsBtn: "Получить награды",
    compoundBtn: "Реинвестировать",
    approveToken: "Одобрить BANMAO",
    selectLockDuration: "Выберите период блокировки",
    // Energy Sphere Display
    sphereRewardPool: "Пул наград",
    sphereTVL: "TVL",
    sphereTotalShares: "Всего долей",
    sphereRewardRate: "Награда/день",
    sphereStatus: "Статус",
    sphereHealthy: "Здоровый",
    sphereUnhealthy: "Нестабильный",
    sphereTapToToggle: "Нажмите для меню",
    // Stats Panel Extended
    statsTotalShares: "Всего долей",
    statsTotalSharesDesc: "Общее количество долей в пуле стейкинга. Больше долей = большая часть наград.",
    statsRewardRate: "Скорость наград",
    statsRewardRateDesc: "Количество токенов, распределяемых в день из пула наград.",
    statsRewardRatePerSec: "Скорость (в секунду)",
    statsRewardRatePerSecDesc: "Исходная скорость вознаграждения из контракта в токенах/сек (для всей системы).",
    statsDaysLeft: "Дней осталось",
    statsDaysLeftDesc: "Расчётное количество дней до исчерпания пула наград.",
    statsMinStake: "Мин. стейк",
    statsMinStakeDesc: "Минимальное количество токенов для создания новой позиции стейкинга.",
    statsMaxStake: "Макс. стейк",
    statsMaxStakeDesc: "Максимальное количество токенов для стейкинга на кошелёк.",
    statsPenalty: "Штраф за вывод",
    statsPenaltyDesc: "Процент штрафа при выводе до окончания периода блокировки.",
    statsGracePeriod: "Льготный период",
    statsGracePeriodDesc: "Период после окончания блокировки для вывода без штрафа.",
    statsVipTier: "VIP уровень",
    statsVipTierDesc: "Ваш VIP статус на основе суммы стейкинга. Выше уровень = больше бонусов.",
    statsPendingReward: "Ожидающие награды",
    statsPendingRewardDesc: "Ваши накопленные награды, ожидающие получения или реинвестирования.",
    statsTotalLockedDesc: "Общая сумма токенов, заблокированных в контракте стейкинга.",
    statsRewardPoolDesc: "Оставшиеся токены в пуле наград для распределения.",
    statsYourStakeDesc: "Ваша личная сумма стейкинга по всем активным позициям.",
    statsDays: "дней",
    statsHours: "часов",
    statsClickForInfo: "Нажмите на статистику для подробностей",
    tooltipTapToClose: "Нажмите, чтобы закрыть",
    // Common UI
    closeBtn: "Закрыть",
    // Stats section headers
    stakingContractStats: "Статистика контракта",
    stakingPersonalStats: "Ваша информация",
    // Wallet balance
    walletBalance: "Баланс кошелька",
    walletBalanceDesc: "Ваш текущий баланс токенов в подключенном кошельке, доступный для стейкинга.",
    // Unstake Annotations
    unstakeEarlyTitle: "⚠️ Заблокировано",
    unstakeEarlyDesc: "Период блокировки еще не завершен.",
    unstakeGraceTitle: "⏰ Льготный период",
    unstakeGraceDesc: "Блокировка завершена! Окно бесплатной разблокировки активно.",
    unstakeAfterTitle: "✅ Полностью разблокировано",
    unstakeAfterDesc: "Разблокируйте в любое время бесплатно.",
    unstakePenaltyWarning: "Комиссия за раннюю разблокировку:",
    unstakeNoPenalty: "Бесплатно - Разблокируйте сейчас!",
    unstakeLockRemaining: "До конца блокировки:",
    unstakeGraceRemaining: "До конца льготного периода:",
    unstakeGracePeriodNote: "После окончания блокировки у вас есть",
    unstakeGracePeriodNoteFree: "для бесплатной разблокировки",
    unstakeLockEnded: "Блокировка завершена",
    unstakeStatus: "Статус",
    // Energy Sphere Refined
    spherePoolStats: "СТАТИСТИКА ПУЛА",
    sphereMyStats: "МОЯ СТАТИСТИКА",
    statsRateDaily: "Скорость (в день)",
    statsRatePerSec: "СКОРОСТЬ/СЕК",
    statsMyStake: "Мой стейк",
    statsPending: "Ожидание",
    // Orb Labels
    orbStats: "Стат.",
    orbStake: "Стейк",
    orbUnstake: "Вывод",
    orbClaim: "Получить",
    orbCompound: "Реинвест",
    // Sphere Hint
    tapSphereHint: "Нажмите на сферу",
    // Claim History Panel
    claimHistoryTitle: "История получения наград",
    claimHistoryContract: "Контракт стейкинга",
    claimHistoryAmount: "Сумма",
    claimHistoryTime: "Время",
    claimHistoryViewTx: "Смотреть TX",
    claimHistoryNoRecords: "Нет записей о получении",
    claimHistoryLoading: "Загрузка истории...",
    claimHistoryShowingRecords: "Показано {count} записей",
    claimHistoryLoadError: "Не удалось загрузить историю",
    claimHistorySearchExplorer: "Искать в Explorer",
    claimHistoryJustNow: "Только что",
    claimHistoryMinutesAgo: "{n} мин. назад",
    claimHistoryHoursAgo: "{n} ч. назад",
    claimHistoryDaysAgo: "{n} дн. назад",
    claimHistoryExplorerGuide: "Для поиска старой истории введите \"claimReward\" в Explorer",
    claimHistorySearchTip: "💡 Совет: Введите \"claimReward\" в поиске для просмотра всех транзакций",
};
