// Vietnamese translations
import type { LandingTranslations } from './index';

export const vi: LandingTranslations = {
    logoTitle: "BANMAO NEBULA",
    tokenStats: "THỐNG KÊ TOKEN",
    totalSupply: "TỔNG CUNG:",
    circulating: "Đang lưu hành",
    burned: "Đã đốt",
    tokenDistribution: "Phân bổ Token",
    holders: "NGƯỜI GIỮ",
    globalHolders: "TỔNG NGƯỜI GIỮ",
    marketCap: "Vốn hóa",
    liquidity: "Thanh khoản",
    token: "Token",
    time: "Thời gian",
    priceFeed: "GIÁ TOKEN",
    network: "MẠNG:",
    price: "GIÁ:",
    change24h: "24H",
    mcap: "VỐN HÓA:",
    buyToken: "MUA $banmao",
    joinMission: "THAM GIA",
    gamefi: "GameFi",
    collection: "Bộ sưu tập",
    installApp: "CÀI ĐẶT APP",
    installDesc: "Thêm vào màn hình để truy cập nhanh!",
    installNow: "Cài đặt",
    howToInstall: "Hướng dẫn",
    language: "NGÔN NGỮ",
    selectLang: "Chọn ngôn ngữ",
    settings: "CÀI ĐẶT",
    theme: "GIAO DIỆN",
    sound: "ÂM THANH",
    minimizedApps: "ỨNG DỤNG THU NHỎ",
    clickToRestore: "Nhấn để khôi phục",
    appsMinimized: "ứng dụng thu nhỏ",
    volume24h: "KL 24H",
    transactions24h: "GD 24H",
    totalTradeVolume: "$banmao Đã GD",
    community: "CỘNG ĐỒNG",
    joinUs: "Tham Gia",
    dataVoid: "HỐ ĐEN",
    dataVoidWarning: "⚠️ Xóa TẤT CẢ dữ liệu?",
    dataVoidConfirm: "XÓA HẾT",
    dataVoidCancel: "HỦY",
    dataVoidCleared: "✓ Đã xóa sạch!",
    tokenInfoTitle: "VỀ BANMAO",
    tokenInfoDesc: "Banmao được sinh ra từ sự kết hợp thú vị giữa mèo 🐱 và chuối 🍌. Tên này pha trộn tiếng Anh và tiếng Trung — \"Banana\" và \"Māo (猫, mèo trong tiếng Trung)\" — tạo thành Banmao, biểu tượng của sự hài hước, đoàn kết và sáng tạo. Đây không chỉ là một cái tên, mà là tinh thần kết hợp Đông và Tây, vui vẻ và ý nghĩa, để xây dựng một meme sống động.",
    totalBurned: "TỔNG ĐÃ ĐỐT 🔥",
    burnHistory: "Xem Lịch sử & Đóng góp",
    burnDescription: "Lịch sử đốt & donate ví cộng đồng. Mọi $BANMAO dùng để đốt, phát triển & sự kiện.",
    burnButton: "🔥 Đốt 🎁",
    defiBurnName: "Đốt/Góp",
    defiBurnDesc: "Góp $BANMAO vào quỹ đốt. Xếp hạng và vinh danh!",
    defiBurnDetails: "Hỗ trợ cộng đồng bằng cách góp $BANMAO. Xếp hạng được ghi nhận. Ví cộng đồng dùng để đốt và phát triển.",
    defiBurnCommunityWallet: "Ví Cộng Đồng",
    // GameFi Hub
    gamefiZone: "GameFi Arena",
    gamefiSubtitle: "Chọn trò chơi để bắt đầu cuộc phiêu lưu",
    gamefiBack: "Quay lại",
    gamefiPlayNow: "Chơi ngay",
    gamefiLive: "TRỰC TIẾP",
    gamefiComingSoon: "Sắp ra mắt",
    gamefiMaintenance: "Bảo trì",
    gamefiRpsName: "OẲN TÙ TÌ",
    gamefiRpsDesc: "Trò chơi Kéo-Búa-Bao PvP on-chain trên XLayer. Sử dụng $BANMAO tokens và thách đấu người chơi khác để giành phần thưởng crypto thực!",
    gamefiSnakeName: "BANMAO SNAKE",
    gamefiSnakeDesc: "Game Snake kinh điển với phần thưởng crypto. Thu thập điểm, leo bảng xếp hạng và nhận rewards bằng $BANMAO tokens!",
    gamefiSlotsName: "BANMAO SLOTS",
    gamefiSlotsDesc: "Trò chơi quay thưởng công bằng! Quay để thắng lên đến 200x lượt tham gia cộng jackpot lũy tiến. Sử dụng tính ngẫu nhiên on-chain!",
    gamefiSlotsHowToPlay: "Tham gia, quay vòng! Khớp 3+ biểu tượng để thắng. 5x Banmao = JACKPOT!",
    // Miner
    gamefiMinerName: "BANMAO MINER",
    gamefiMinerDesc: "Game đào vàng cổ điển theo chủ đề crypto! Bắt tokens và gems để kiếm điểm, rồi claim $BANMAO trên XLayer!",
    gamefiMinerDetails: "Bắt tokens 🪙 và gems 💎 để kiếm điểm. Tránh rug pulls 💣! Đạt mục tiêu trước khi hết giờ để nhận $BANMAO!",
    gamefiMinerHowToPlay: "Nhấn để thả móc. Bắt items giá trị để kiếm điểm. Đạt mục tiêu trước khi hết giờ!",
    // FOMO
    gamefiFomoName: "BANMAO FOMO",
    gamefiFomoDesc: "Jackpot người tấn công cuối cùng trên XLayer! Trả 2,000 $BANMAO mỗi lượt tấn công để tranh giải thưởng liên tục tăng trưởng. Người tấn công cuối thắng 75% jackpot, Top 10 chia 25%. Tự động đốt 1% mỗi lượt!",
    gamefiFomoDetails: "Mỗi lượt tấn công tốn 2,000 $BANMAO. Phân phối: 75% Jackpot, 17% Cổ tức (chia cho tất cả người tấn công), 5% Quỹ giống (vòng tiếp), 2% Staking, 1% Tự động đốt. Hệ thống đồng hồ kép: Timer mềm (6 giờ, reset mỗi lượt) + Timer cứng (120 giờ, giảm ~100 phút/lượt). Khi bất kỳ timer nào về 0, người tấn công cuối thắng 75% jackpot và Top 10 chia 25%. Hệ thống VIP — càng tích cực cooldown càng ngắn. Cửa sổ nhận thưởng 2 giờ sau khi vòng kết thúc.",
    gamefiFomoHowToPlay: "Kết nối ví → Phê duyệt $BANMAO → Tấn công (1-10 lần/giao dịch, 2,000 token mỗi lần). Mỗi lượt tấn công reset timer mềm 6 giờ và rút ngắn timer cứng 120 giờ. Hãy là người tấn công cuối khi timer hết để nhận 75% jackpot! Tấn công nhiều hơn để lọt Top 10 nhận thêm thưởng.",
    gamefiWorldCupName: "BANMAO CUP",
    gamefiWorldCupDesc: "Stake $BANMAO cho đội bóng yêu thích! APY động theo kết quả trận đấu thật. Đội thắng nhận thưởng cao hơn, đội bị loại bị đóng băng.",
    gamefiWorldCupDetails: "32 pool đội tuyển với hệ số APY động. Stake cho đội thắng → nhận nhiều hơn. Đội thắng nhận boost 1.5x APY, đội thua giảm 0.8x. Đội bị loại bị đóng băng — rút stake không phạt. Pool đội vô địch nhận bonus 5x APY!",
    gamefiFooter: "Developed by ＤＯＲＥＭＯＮ",
    gamefiMoreGames: "Thêm game sắp ra mắt!",
    gamefiLoadingGame: "Đang tải game...",
    gamefiRpsHowToPlay: "Tạo hoặc tham gia phòng, dùng $BANMAO, chọn Kéo/Búa/Bao. Người thắng nhận toàn bộ phần thưởng!",
    gamefiSnakeHowToPlay: "Dùng phím mũi tên hoặc vuốt để điều khiển rắn. Thu thập xu & power-up để tăng điểm và nhận thưởng!",
    gamefiAbout: "Giới thiệu",
    gamefiHowToPlay: "Cách chơi",
    gamefiSmartContract: "Hợp đồng thông minh",
    gamefiViewExplorer: "Xem trên Explorer",
    // Donor Modal
    totalDonated: "Tổng đã Donate",
    donationCount: "Số lần Donate",
    times: "lần",
    loading: "Đang tải...",
    noData: "Không có dữ liệu",
    editProfile: "Chỉnh sửa hồ sơ",
    anonymous: "Ẩn danh",
    displayName: "Tên hiển thị",
    displayNamePlaceholder: "Nhập tên của bạn...",
    topDonors: "Nhà Tài Trợ",
    // Browser Notice
    browserNoticeTitle: "🌐 Trải nghiệm tốt nhất trên Chrome",
    browserNoticeDesc: "GameFi hoạt động tốt nhất trên trình duyệt Google Chrome. Khuyến nghị sử dụng trên cả PC và điện thoại.",
    browserNoticeMobile: "📱 Mẹo Mobile: Tăng mật độ DPI/hiển thị màn hình trước khi chơi để có trải nghiệm tốt hơn!",
    browserNoticeDesktop: "💻 Desktop: GameFi hoạt động hoàn hảo nhất trên máy tính!",
    browserNoticeDownload: "Tải Chrome",
    browserNoticeInstalled: "Đã cài",
    browserNoticeClose: "Đã hiểu!",
    // Staking
    staking: "Staking",
    stakingTitle: "BANMAO STAKING",
    stakingSubtitle: "Khóa $BANMAO để nhận phần thưởng",
    stakingLock: "Khóa Token",
    stakingUnlock: "Mở khóa",
    stakingRewards: "Nhận Thưởng",
    stakingAPY: "APY",
    stakingTotalLocked: "Tổng Khóa",
    stakingYourStake: "Stake Của Bạn",
    stakingLockPeriod: "Thời Gian Khóa",
    stakingDays: "ngày",
    stakingEarned: "Đã Kiếm",
    stakingPending: "Thưởng Chờ Nhận",
    backToHub: "Quay lại DeFi Hub",
    // DeFi Hub
    defiHub: "DeFi Hub",
    defiExploreTitle: "Khám Phá DeFi",
    defiExploreSubtitle: "Kiếm thưởng, cung cấp thanh khoản và phát triển $BANMAO của bạn",
    defiDisabled: "DeFi Tạm Ngưng",
    defiDisabledDesc: "Tính năng DeFi đang được bảo trì. Vui lòng quay lại sau.",
    defiBackHome: "Về Trang Chủ",
    defiTVL: "Tổng Giá Trị Khóa",
    defiActiveUsers: "Người Dùng",
    defiBestAPY: "APY Cao Nhất",
    defiServices: "Dịch Vụ",
    defiLive: "Hoạt Động",
    defiComingSoon: "Sắp Ra Mắt",
    defiEnter: "Vào",
    defiTvlTooltip: "Tổng giá trị $BANMAO đang được khóa trong các hợp đồng thông minh.",
    defiStakersTooltip: "Tổng số lượng người đang tham gia Staking.",
    defiApyTooltip: "Tỷ suất lợi nhuận hàng năm ước tính.",
    defiBurnTooltip: "Tổng lượng $BANMAO đã bị đốt vĩnh viễn ra khỏi nguồn cung.",
    // DeFi Services
    defiStakingName: "Staking",
    defiStakingDesc: "Khóa $BANMAO, nhận thưởng APY đến 75%",
    defiStakingDetails: "Tối đa hóa lợi nhuận bằng cách khóa token $BANMAO. Khóa càng lâu, hệ số thưởng (Share Booster) càng cao.\n\nCơ chế hoạt động:\n• Thời gian khóa: Tùy chọn từ linh hoạt đến 365 ngày.\n• Hệ số nhân: Tăng gấp 2 lần số lượng cổ phần cho kỳ hạn dài.\n• Phạt rút sớm: Rút trước hạn sẽ chịu phí phạt, phí này được đưa lại vào bể thưởng.\n• Phần thưởng: Trả bằng $BANMAO, có thể nhận bất cứ lúc nào.\n\nSmart Contract đảm bảo mọi tính toán minh bạch trên chuỗi.",
    defiPoolsName: "Pool Thanh Khoản",
    defiPoolsDesc: "Cung cấp thanh khoản để kiếm phí giao dịch và thưởng",
    defiFarmingName: "Yield Farming",
    defiFarmingDesc: "Farm $BANMAO bằng cách cung cấp thanh khoản",
    defiLendingName: "Cho vay",
    defiLendingDesc: "Cho vay tài sản để nhận lãi",
    defiAirdropName: "Airdrop",
    defiAirdropDesc: "Công cụ cộng đồng để airdrop \$BANMAO đến các ví chưa nắm giữ token. Tiện hơn gửi từng cái!",
    defiAirdropDetails: "Công cụ mạnh mẽ cho cộng đồng \$BANMAO phân phối token đến ví mới trên XLayer hàng loạt. Quét ví hoạt động, tự động loại ví đã có \$BANMAO, gửi đến hàng trăm địa chỉ trong một phiên. Hỗ trợ nhập thủ công, quét blockchain và nhập CSV với tốc độ lên đến x20.",
    // Staking Infographic Bullets
    defiStakingIntro: "Tối đa hóa lợi nhuận bằng cách khóa token $BANMAO. Khóa càng lâu, hệ số thưởng càng cao.",
    defiStakingBullet1Title: "Thời gian khóa",
    defiStakingBullet1Desc: "Tùy chọn từ linh hoạt đến 365 ngày.",
    defiStakingBullet2Title: "Hệ số nhân",
    defiStakingBullet2Desc: "Tăng gấp 2 lần cổ phần cho kỳ hạn dài.",
    defiStakingBullet3Title: "Phạt rút sớm",
    defiStakingBullet3Desc: "Phí phạt được đưa lại vào bể thưởng.",
    defiStakingBullet4Title: "Phần thưởng",
    defiStakingBullet4Desc: "Trả bằng $BANMAO, nhận bất cứ lúc nào.",
    defiStakingOutro: "Smart Contract đảm bảo mọi tính toán minh bạch trên chuỗi.",
    // Burn Infographic Bullets
    defiBurnIntro: "Hỗ trợ cộng đồng bằng cách góp $BANMAO.",
    defiBurnBullet1Title: "Đóng góp",
    defiBurnBullet1Desc: "Gửi $BANMAO vào ví cộng đồng.",
    defiBurnBullet2Title: "Xếp hạng",
    defiBurnBullet2Desc: "Mọi đóng góp được ghi nhận và xếp hạng.",
    defiBurnBullet3Title: "Quỹ cộng đồng",
    defiBurnBullet3Desc: "Dùng để đốt, phát triển & sự kiện.",
    defiBurnOutro: "Mỗi token đóng góp đều củng cố hệ sinh thái Banmao.",
    // Airdrop Infographic Bullets
    defiAirdropIntro: "Phân phối $BANMAO đến ví mới trên XLayer hàng loạt.",
    defiAirdropBullet1Title: "Quét ví",
    defiAirdropBullet1Desc: "Tìm ví hoạt động chưa có $BANMAO.",
    defiAirdropBullet2Title: "Gửi hàng loạt",
    defiAirdropBullet2Desc: "Gửi đến hàng trăm địa chỉ trong một phiên.",
    defiAirdropBullet3Title: "Đa nhập liệu",
    defiAirdropBullet3Desc: "Nhập thủ công, quét blockchain, hoặc CSV.",
    defiAirdropOutro: "Hỗ trợ tốc độ hàng loạt lên đến x20.",
    // Staking Page UI
    stakingAmountToStake: "Số Lượng Stake",
    stakingAvailableBalance: "Số Dư Khả Dụng",
    stakingSelectLockOption: "Gói Khóa Đã Chọn",
    stakingMultiplier: "Hệ Số Nhân",
    stakingBoost: "Boost",
    stakingFlexible: "Linh Hoạt",
    stakingLockTokens: "Khóa Token $BANMAO",
    stakingUnstakeTokens: "Rút Stake",
    stakingAmountToUnstake: "Số Lượng Rút",
    stakingClaim: "Nhận Thưởng",
    stakingCompound: "Gộp Lãi",
    stakingEmergencyWithdraw: "Rút Khẩn Cấp",
    stakingRewardPool: "Pool Thưởng",
    stakingContractHealth: "Sức Khỏe Contract",
    stakingHealthy: "Khỏe Mạnh",
    stakingCheckRequired: "Cần Kiểm Tra",
    stakingRewardsLeft: "Thưởng còn lại",
    stakingDonateTitle: "Đóng Góp Vào Pool Thưởng",
    stakingDonateDesc: "Hỗ trợ cộng đồng bằng cách đóng góp token vào pool thưởng.",
    stakingDonateButton: "Đóng Góp",
    stakingApprove: "Phê Duyệt",
    stakingDonateTip: "Token đóng góp sẽ được phân phối cho tất cả stakers.",
    stakingDonateAction: "Đóng Góp",
    stakingDonateNote: "Hỗ trợ dự án bằng $BANMAO tokens",
    stakingWaitWallet: "Đang chờ xác nhận ví...",
    stakingTxPending: "Giao dịch đang xử lý...",
    stakingTxSuccess: "Giao dịch thành công! ✅",
    stakingAvailableToUnstake: "Hiện có để rút",
    stakingEstimatedEarnings: "Ước Tính Lợi Nhuận",
    stakingStakeAmount: "Số Lượng Stake",
    stakingEffectiveShares: "Shares Thực Tế",
    stakingCalculatedNote: "Thời gian khóa càng lâu = Shares càng nhiều = Thưởng càng cao",
    stakingTokensToReceive: "Bạn sẽ nhận được",
    stakingPenaltyWarning: "Phí rút sớm",
    // Panel Titles & Labels
    panelStats: "Thống Kê Hệ Thống",
    panelStake: "Stake Token",
    panelUnstake: "Rút Stake",
    panelClaim: "Nhận Thưởng",
    panelCompound: "Gộp Lãi",
    panelClose: "Đóng",
    // Panel Content
    balanceLabel: "Số Dư",
    stakedLabel: "Đã Stake",
    amountToStake: "Số lượng stake",
    amountToUnstake: "Số lượng rút",
    pendingRewards: "Thưởng Chờ Nhận",
    noRewardsMessage: "Không có thưởng để nhận.",
    autoCompoundDesc: "Tự động gộp phần thưởng vào stake",
    confirmStake: "Xác Nhận Stake",
    confirmUnstake: "Xác Nhận Rút",
    claimRewardsBtn: "Nhận Thưởng",
    compoundBtn: "Gộp Lãi",
    approveToken: "Phê Duyệt BANMAO",
    selectLockDuration: "Chọn Thời Gian Khóa",
    // Energy Sphere Display
    sphereRewardPool: "Pool Thưởng",
    sphereTVL: "TVL",
    sphereTotalShares: "Tổng Cổ Phần",
    sphereRewardRate: "Thưởng/ngày",
    sphereStatus: "Trạng Thái",
    sphereHealthy: "Ổn Định",
    sphereUnhealthy: "Không Ổn Định",
    sphereTapToToggle: "Nhấn để mở/đóng menu",
    // Stats Panel Extended
    statsTotalShares: "Tổng Cổ Phần",
    statsTotalSharesDesc: "Tổng số cổ phần trong pool staking. Càng nhiều cổ phần = càng nhiều phần thưởng.",
    statsRewardRate: "Tốc Độ Thưởng",
    statsRewardRateDesc: "Số token được phân phối làm phần thưởng mỗi ngày từ pool thưởng.",
    statsRewardRatePerSec: "Tốc Độ (Mỗi Giây)",
    statsRewardRatePerSecDesc: "Tốc độ thưởng gốc từ hợp đồng tính theo token/giây (toàn hệ thống).",
    statsDaysLeft: "Số Ngày Còn Lại",
    statsDaysLeftDesc: "Ước tính số ngày cho đến khi pool thưởng cạn kiệt theo tốc độ hiện tại.",
    statsMinStake: "Stake Tối Thiểu",
    statsMinStakeDesc: "Số token tối thiểu cần có để tạo một vị trí stake mới.",
    statsMaxStake: "Stake Tối Đa",
    statsMaxStakeDesc: "Số token tối đa được phép stake cho mỗi ví.",
    statsPenalty: "Phí Rút Sớm",
    statsPenaltyDesc: "Phần trăm phí bị trừ khi rút stake trước khi hết thời gian khóa.",
    statsGracePeriod: "Thời Gian Ân Hạn",
    statsGracePeriodDesc: "Khoảng thời gian sau khi hết khóa mà bạn có thể rút mà không bị phạt.",
    statsVipTier: "Hạng VIP",
    statsVipTierDesc: "Cấp bậc VIP dựa trên tổng số tiền stake. Hạng cao hơn nhận thưởng bonus.",
    statsPendingReward: "Thưởng Chờ Nhận",
    statsPendingRewardDesc: "Phần thưởng tích lũy của bạn đang chờ được nhận hoặc gộp lãi.",
    statsTotalLockedDesc: "Tổng số token hiện đang bị khóa trong hợp đồng staking.",
    statsRewardPoolDesc: "Số token còn lại trong pool thưởng có thể phân phối.",
    statsYourStakeDesc: "Số tiền stake cá nhân của bạn trong tất cả các vị trí stake.",
    statsDays: "ngày",
    statsHours: "giờ",
    statsClickForInfo: "Nhấn vào thống kê để xem chi tiết",
    tooltipTapToClose: "Nhấn để đóng",
    // Common UI
    closeBtn: "Đóng",
    // Stats section headers
    stakingContractStats: "Thống Kê Hợp Đồng",
    stakingPersonalStats: "Thông Tin Cá Nhân",
    // Wallet balance
    walletBalance: "Số Dư Ví",
    walletBalanceDesc: "Số token hiện có trong ví đã kết nối của bạn, sẵn sàng để stake.",
    // Unstake Annotations
    unstakeEarlyTitle: "⚠️ Đang Khóa",
    unstakeEarlyDesc: "Chưa hết thời gian khóa.",
    unstakeGraceTitle: "⏰ Thời Gian Ân Hạn",
    unstakeGraceDesc: "Đã hết khóa! Đang trong thời gian rút miễn phí.",
    unstakeAfterTitle: "✅ Đã Mở Khóa",
    unstakeAfterDesc: "Rút bất cứ lúc nào miễn phí.",
    unstakePenaltyWarning: "Phí rút sớm:",
    unstakeNoPenalty: "Miễn phí - Rút ngay!",
    unstakeLockRemaining: "Hết khóa sau:",
    unstakeGraceRemaining: "Hết ân hạn sau:",
    unstakeGracePeriodNote: "Sau khi hết khóa, bạn có",
    unstakeGracePeriodNoteFree: "để rút miễn phí",
    unstakeLockEnded: "Đã hết khóa",
    unstakeStatus: "Trạng thái",
    // Energy Sphere Refined
    spherePoolStats: "POOL THƯỞNG",
    sphereMyStats: "CỦA TÔI",
    statsRateDaily: "Tốc Độ/Ngày",
    statsRatePerSec: "TỐC ĐỘ/S",
    statsMyStake: "Đã Stake",
    statsPending: "Chờ Nhận",
    // Orb Labels
    orbStats: "Thống Kê",
    orbStake: "Stake",
    orbUnstake: "Rút",
    orbClaim: "Nhận",
    orbCompound: "Gộp",
    // Sphere Hint
    tapSphereHint: "Chạm Quả Cầu Để Mở",
    // Claim History Panel
    claimHistoryTitle: "Lịch Sử Nhận Thưởng",
    claimHistoryContract: "Hợp Đồng Staking",
    claimHistoryAmount: "Số Lượng",
    claimHistoryTime: "Thời Gian",
    claimHistoryViewTx: "Xem TX",
    claimHistoryNoRecords: "Chưa có lịch sử nhận thưởng",
    claimHistoryLoading: "Đang tải lịch sử...",
    claimHistoryShowingRecords: "Hiển thị {count} lần nhận gần đây",
    claimHistoryLoadError: "Không thể tải lịch sử",
    claimHistorySearchExplorer: "Tìm trên Explorer",
    claimHistoryJustNow: "Vừa xong",
    claimHistoryMinutesAgo: "{n} phút trước",
    claimHistoryHoursAgo: "{n} giờ trước",
    claimHistoryDaysAgo: "{n} ngày trước",
    claimHistoryExplorerGuide: "Để tìm lịch sử cũ hơn, nhập \"claimReward\" trên Explorer",
    claimHistorySearchTip: "💡 Mẹo: Nhập \"claimReward\" vào ô tìm kiếm để xem tất cả giao dịch nhận thưởng",
};
