// Chinese translations
import type { LandingTranslations } from './index';

export const zh: LandingTranslations = {
    logoTitle: "BANMAO 星云",
    tokenStats: "代币统计",
    totalSupply: "总供应量:",
    circulating: "流通量",
    burned: "已销毁",
    tokenDistribution: "代币分配",
    holders: "持有人",
    globalHolders: "全球持有者",
    marketCap: "市值",
    liquidity: "流动性",
    token: "代币",
    time: "时间",
    priceFeed: "价格动态",
    network: "网络:",
    price: "价格:",
    change24h: "24H变化",
    mcap: "市值:",
    buyToken: "买 $banmao",
    joinMission: "加入任务",
    gamefi: "GameFi",
    collection: "收藏集",
    installApp: "安装应用",
    installDesc: "添加到主屏幕快速访问！",
    installNow: "立即安装",
    howToInstall: "安装指南",
    language: "语言",
    selectLang: "选择语言",
    settings: "设置",
    theme: "主题",
    sound: "声音",
    minimizedApps: "已最小化应用",
    clickToRestore: "点击恢复",
    appsMinimized: "个应用已最小化",
    volume24h: "24H成交量",
    transactions24h: "24H交易",
    totalTradeVolume: "$banmao交易量",
    community: "社区",
    joinUs: "加入我们",
    dataVoid: "数据黑洞",
    dataVoidWarning: "⚠️ 删除所有数据？",
    dataVoidConfirm: "确认删除",
    dataVoidCancel: "取消",
    dataVoidCleared: "✓ 已清除！",
    tokenInfoTitle: "关于 BANMAO",
    tokenInfoDesc: "Banmao诞生于猫🐱和香蕉🍌的有趣融合。这个名字混合了英语和中文——\"Banana\"和\"Māo (猫)\"——创造出Banmao，这是幽默、团结和创造力的象征。这不仅仅是一个名字，更是一种融合东西方、趣味与意义的精神，用于创建一个活生生的meme。",
    totalBurned: "总销毁 🔥",
    burnHistory: "查看历史和捐赠",
    burnDescription: "销毁历史和社区钱包捐赠。所有$BANMAO用于销毁、开发和活动。",
    burnButton: "🔥 销毁 🎁",
    defiBurnName: "销毁/捐赠",
    defiBurnDesc: "捐赠$BANMAO，上榜获得荣誉！",
    defiBurnDetails: "通过捐赠$BANMAO支持社区，排行榜记录贡献。",
    defiBurnCommunityWallet: "社区钱包",
    // GameFi Hub
    gamefiZone: "GameFi 区域",
    gamefiSubtitle: "选择游戏开始冒险",
    gamefiBack: "返回",
    gamefiPlayNow: "立即游戏",
    gamefiLive: "在线",
    gamefiComingSoon: "即将推出",
    gamefiMaintenance: "维护中",
    gamefiRpsName: "BANMAO 石头剪刀布",
    gamefiRpsDesc: "XLayer链上石头剪刀布PvP游戏。使用$BANMAO代币，挑战其他玩家赢取真正的加密奖励！",
    gamefiSnakeName: "BANMAO 贪吃蛇",
    gamefiSnakeDesc: "经典贪吃蛇游戏，带有加密奖励。收集分数，攀登排行榜，用$BANMAO代币获得奖励！",
    gamefiSlotsName: "BANMAO 旋转乐",
    gamefiSlotsDesc: "公平透明的旋转游戏！旋转赢取高达200倍投入加累积奖金。由链上随机性驱动！",
    gamefiSlotsHowToPlay: "参与，旋转！匹配3+符号赢取奖励。5个Banmao = 大奖！",
    // Miner
    gamefiMinerName: "BANMAO 矿工",
    gamefiMinerDesc: "经典挖矿游戏加密风格！抓取代币和宝石赚取积分，然后在XLayer上领取$BANMAO奖励！",
    gamefiMinerDetails: "抓取代币🪙和宝石💎赚取积分。避开跑路炸弹💣！在时间结束前达到目标分数领取$BANMAO！",
    gamefiMinerHowToPlay: "点击放下钩子。抓取有价值的物品赚取积分。在时间结束前达到目标分数！",
    // FOMO
    gamefiFomoName: "BANMAO FOMO",
    gamefiFomoDesc: "XLayer上的策略型末位竞拍！每次攻击花费2,000 $BANMAO竞争不断增长的奖池。最后攻击者赢得75%奖池，Top 10攻击者瓜分25%。每次攻击自动销毁1%！",
    gamefiFomoDetails: "每次攻击消耗2,000 $BANMAO。资金分配：75%进入奖池，17%红利（所有攻击者共享），5%种子基金（下一轮），2%质押奖励，1%自动销毁。双计时器系统：软计时器（6小时，每次攻击重置）和硬计时器（120小时，每次攻击减少约100分钟）。当任一计时器归零，最后攻击者赢得75%奖池，Top 10攻击者瓜分25%。VIP等级系统 — 越活跃冷却越短。回合结束后有2小时领奖窗口。",
    gamefiFomoHowToPlay: "连接钱包 → 授权$BANMAO → 发起攻击（每笔1-10次，每次2,000代币）。每次攻击重置6小时软计时器并缩短120小时硬计时器。在任一计时器归零时成为最后攻击者即可赢得75%奖池！攻击越多排名越高，Top 10还有额外奖励。",
    gamefiFooter: "Developed by ＤＯＲＥＭＯＮ",
    gamefiMoreGames: "更多游戏即将推出！",
    gamefiLoadingGame: "加载游戏中...",
    gamefiRpsHowToPlay: "创建或加入房间，使用$BANMAO代币，选择石头/剪刀/布。赢家获得全部奖励！",
    gamefiSnakeHowToPlay: "使用方向键或滑动来控制蛇。收集金币和道具来增加分数并领取奖励！",
    gamefiAbout: "关于",
    gamefiHowToPlay: "玩法说明",
    gamefiSmartContract: "智能合约",
    gamefiViewExplorer: "在浏览器查看",
    // Donor Modal
    totalDonated: "总捐赠额",
    donationCount: "捐赠次数",
    times: "次",
    loading: "加载中...",
    noData: "暂无数据",
    editProfile: "编辑资料",
    anonymous: "匿名",
    displayName: "显示名称",
    displayNamePlaceholder: "输入您的名称...",
    topDonors: "捐赠者榜",
    // Browser Notice
    browserNoticeTitle: "🌐 Chrome 浏览器体验最佳",
    browserNoticeDesc: "GameFi 在 Google Chrome 浏览器上运行效果最好。推荐在电脑和手机上使用。",
    browserNoticeMobile: "📱 手机提示：游戏前先提高屏幕DPI/显示密度，体验更佳！",
    browserNoticeDesktop: "💻 电脑：GameFi 在电脑上运行最为完美！",
    browserNoticeDownload: "下载 Chrome",
    browserNoticeInstalled: "已安装",
    browserNoticeClose: "知道了！",
    // Staking
    staking: "Staking",
    stakingTitle: "BANMAO 质押",
    stakingSubtitle: "锁定 $BANMAO 赚取奖励",
    stakingLock: "锁定代币",
    stakingUnlock: "解锁",
    stakingRewards: "领取奖励",
    stakingAPY: "年化收益率",
    stakingTotalLocked: "总锁定量",
    stakingYourStake: "您的质押",
    stakingLockPeriod: "锁定期限",
    stakingDays: "天",
    stakingEarned: "已赚取",
    stakingPending: "待领取奖励",
    backToHub: "返回 DeFi Hub",
    // DeFi Hub
    defiHub: "DeFi 中心",
    defiExploreTitle: "探索 DeFi 服务",
    defiExploreSubtitle: "赚取奖励，提供流动性，增长您的 $BANMAO 持仓",
    defiDisabled: "DeFi 暂时关闭",
    defiDisabledDesc: "DeFi 功能正在维护中。请稍后再来。",
    defiBackHome: "返回首页",
    defiTVL: "锁定总值",
    defiActiveUsers: "活跃用户",
    defiBestAPY: "最高年化",
    defiServices: "服务",
    defiLive: "已上线",
    defiComingSoon: "即将推出",
    defiEnter: "进入",
    defiTvlTooltip: "所有智能合约中锁定的 $BANMAO 总量。",
    defiStakersTooltip: "参与质押的用户总数。",
    defiApyTooltip: "年化收益率：预计在一年内获得的收益率。",
    defiBurnTooltip: "永久退出流通的 $BANMAO 总量。",
    // DeFi Services
    defiStakingName: "质押",
    defiStakingDesc: "锁定$BANMAO，APY高达75%",
    defiStakingDetails: "通过锁定 $BANMAO 代币最大化您的收益。锁定越久，奖励倍数越高。\n\n机制：\n• 锁定期：从灵活到 365 天可选。\n• 倍数：长期锁定可获得高达 2 倍的份额。\n• 惩罚：提前解除质押将收取费用，返还至奖励池。\n• 奖励：以 $BANMAO 支付，随时可领取。\n\n智能合约确保所有逻辑在链上透明执行。",
    defiPoolsName: "流动池",
    defiPoolsDesc: "提供流动性赚取交易费和奖励",
    defiFarmingName: "收益农场",
    defiFarmingDesc: "通过提供流动性挖矿 $BANMAO 代币",
    defiLendingName: "借贷",
    defiLendingDesc: "出借资产赚取利息",
    defiAirdropName: "空投",
    defiAirdropDesc: "向 XLayer 活跃钱包分发 $BANMAO",
    defiAirdropDetails: "扫描 XLayer 活跃钱包并批量空投 $BANMAO。已持有 $BANMAO 的钱包自动排除。",
    // Staking Page UI
    stakingAmountToStake: "质押数量",
    stakingAvailableBalance: "可用余额",
    stakingSelectLockOption: "已选锁定方案",
    stakingMultiplier: "乘数",
    stakingBoost: "加成",
    stakingFlexible: "灵活",
    stakingLockTokens: "锁定 $BANMAO 代币",
    stakingUnstakeTokens: "解除质押",
    stakingAmountToUnstake: "解押数量",
    stakingClaim: "领取",
    stakingCompound: "复投",
    stakingEmergencyWithdraw: "紧急提款",
    stakingRewardPool: "奖励池",
    stakingContractHealth: "合约健康",
    stakingHealthy: "健康",
    stakingCheckRequired: "需要检查",
    stakingRewardsLeft: "剩余奖励",
    stakingDonateTitle: "捐赠到奖励池",
    stakingDonateDesc: "通过向奖励池捐赠代币来支持社区。",
    stakingDonateButton: "捐赠",
    stakingApprove: "授权",
    stakingDonateTip: "捐赠的代币将分发给所有质押者。",
    stakingDonateAction: "捐赠",
    stakingDonateNote: "使用 $BANMAO 代币支持项目",
    stakingWaitWallet: "等待钱包确认...",
    stakingTxPending: "交易处理中...",
    stakingTxSuccess: "交易成功! ✅",
    stakingAvailableToUnstake: "可提取余额",
    stakingEstimatedEarnings: "预估收益",
    stakingStakeAmount: "质押数量",
    stakingEffectiveShares: "实际份额",
    stakingCalculatedNote: "质押时间越长 = 份额越多 = 奖励越高",
    stakingTokensToReceive: "您将收到",
    stakingPenaltyWarning: "提早提取手续费",
    // Panel Titles & Labels
    panelStats: "系统统计",
    panelStake: "质押代币",
    panelUnstake: "解除质押",
    panelClaim: "领取奖励",
    panelCompound: "复投",
    panelClose: "关闭",
    // Panel Content
    balanceLabel: "余额",
    stakedLabel: "已质押",
    amountToStake: "质押数量",
    amountToUnstake: "解押数量",
    pendingRewards: "待领取奖励",
    noRewardsMessage: "没有待领取的奖励。",
    autoCompoundDesc: "将奖励自动复投到质押",
    confirmStake: "确认质押",
    confirmUnstake: "确认解押",
    claimRewardsBtn: "领取奖励",
    compoundBtn: "复投",
    approveToken: "授权 BANMAO",
    selectLockDuration: "选择锁定期限",
    // Energy Sphere Display
    sphereRewardPool: "奖励池",
    sphereTVL: "TVL",
    sphereTotalShares: "总份额",
    sphereRewardRate: "奖励/天",
    sphereStatus: "状态",
    sphereHealthy: "健康",
    sphereUnhealthy: "不稳定",
    sphereTapToToggle: "点击切换菜单",
    // Stats Panel Extended
    statsTotalShares: "总份额",
    statsTotalSharesDesc: "质押池中的总份额数量。份额越多 = 奖励份额越大。",
    statsRewardRate: "奖励速度",
    statsRewardRateDesc: "每天从奖励池中分发的代币数量。",
    statsRewardRatePerSec: "速率 (每秒)",
    statsRewardRatePerSecDesc: "合约中的原始奖励速率，按代币/秒计算(全系统)。",
    statsDaysLeft: "剩余天数",
    statsDaysLeftDesc: "根据当前奖励速度，预计奖励池耗尽的天数。",
    statsMinStake: "最低质押",
    statsMinStakeDesc: "创建新质押位置所需的最低代币数量。",
    statsMaxStake: "最高质押",
    statsMaxStakeDesc: "每个钱包允许质押的最大代币数量。",
    statsPenalty: "提前惩罚",
    statsPenaltyDesc: "在锁定期结束前解押时适用的惩罚百分比。",
    statsGracePeriod: "宽限期",
    statsGracePeriodDesc: "锁定期结束后可以无惩罚解押的时间窗口。",
    statsVipTier: "VIP等级",
    statsVipTierDesc: "基于总质押金额的VIP状态。等级越高，奖励越多。",
    statsPendingReward: "待领奖励",
    statsPendingRewardDesc: "您累积的等待领取或复投的奖励。",
    statsTotalLockedDesc: "当前锁定在质押合约中的代币总量。",
    statsRewardPoolDesc: "奖励池中可供分配的剩余代币。",
    statsYourStakeDesc: "您在所有活跃质押位置中的个人质押金额。",
    statsDays: "天",
    statsHours: "小时",
    statsClickForInfo: "点击任意统计查看详情",
    tooltipTapToClose: "点击关闭",
    // Common UI
    closeBtn: "关闭",
    // Stats section headers
    stakingContractStats: "合约统计",
    stakingPersonalStats: "个人信息",
    // Wallet balance
    walletBalance: "钱包余额",
    walletBalanceDesc: "您连接钱包中可用于质押的当前代币余额。",
    // Unstake Annotations
    unstakeEarlyTitle: "⚠️ 锁定中",
    unstakeEarlyDesc: "锁定期尚未结束。",
    unstakeGraceTitle: "⏰ 宽限期",
    unstakeGraceDesc: "锁定结束！免费解锁窗口已激活。",
    unstakeAfterTitle: "✅ 已解锁",
    unstakeAfterDesc: "随时可免费解锁。",
    unstakePenaltyWarning: "提前解锁费用：",
    unstakeNoPenalty: "免费 - 立即解锁！",
    unstakeLockRemaining: "锁定到期：",
    unstakeGraceRemaining: "宽限期剩余：",
    unstakeGracePeriodNote: "锁定结束后，您有",
    unstakeGracePeriodNoteFree: "免费解锁",
    unstakeLockEnded: "锁定结束",
    unstakeStatus: "状态",
    // Energy Sphere Refined
    spherePoolStats: "POOL 统计",
    sphereMyStats: "我的统计",
    statsRateDaily: "速率 (每日)",
    statsRatePerSec: "速率/秒",
    statsMyStake: "我的质押",
    statsPending: "待领取",
    // Orb Labels
    orbStats: "统计",
    orbStake: "质押",
    orbUnstake: "解押",
    orbClaim: "领取",
    orbCompound: "复投",
    // Sphere Hint
    tapSphereHint: "点击球体打开",
    // Claim History Panel
    claimHistoryTitle: "领取奖励历史",
    claimHistoryContract: "质押合约",
    claimHistoryAmount: "数量",
    claimHistoryTime: "时间",
    claimHistoryViewTx: "查看TX",
    claimHistoryNoRecords: "暂无领取记录",
    claimHistoryLoading: "加载历史中...",
    claimHistoryShowingRecords: "显示{count}条最近记录",
    claimHistoryLoadError: "无法加载历史",
    claimHistorySearchExplorer: "在浏览器中搜索",
    claimHistoryJustNow: "刚刚",
    claimHistoryMinutesAgo: "{n}分钟前",
    claimHistoryHoursAgo: "{n}小时前",
    claimHistoryDaysAgo: "{n}天前",
    claimHistoryExplorerGuide: "要查找更早的记录，请在浏览器中搜索 \"claimReward\"",
    claimHistorySearchTip: "💡 提示：在搜索框中输入 \"claimReward\" 查看所有领取交易",
};
